### PR TITLE
[ELY-2394] Add the ability to search for blog posts on the Elytron Blogs Page

### PR DESCRIPTION
**Pull request by gabrielpadilh4**
Fixes: https://issues.redhat.com/browse/ELY-2394

Preview: https://gabrielpadilh4.github.io/wildfly-elytron/

### CODE REVIEW

**Comment by gabrielpadilh4** [comment]
Hello Team, just as a preview of how it is working on UI, it is using the post title, synopsis and tags as a filter. I'm open for feedback. Thank you. 

Here are some screenshots:

Search bar:
image

Search working:
image

No results found:
image

**Comment by PrarthonaPaul** [comment]
Hi @gabrielpadilh4 
Thank you for the PR! 
Would you be able to submit the PR from the develop branch of your fork? This way we will be able to see the preview of what the new search option looks like. 
You can use the `cherry-pick` option in git to move your commit from this branch to develop. 
Please let me know if you have any questions.

**Comment by gabrielpadilh4** [comment]
Hello @PrarthonaPaul do you meant me to do this ? https://github.com/wildfly-security/wildfly-elytron/pull/2056

**Comment by PrarthonaPaul** [comment]
> Hello @PrarthonaPaul do you meant to do this ? #2056

Thats perfect! 
If you could also include the link to preview on the description that would be awesome. 
It would be `https://<your github username>.github.io/wildfly-elytron/blog/`

**Comment by gabrielpadilh4** [comment]
I updated both PRs with the link @PrarthonaPaul thanks.

**Pull request closed without merging**
