### PR TITLE
[ELY-1815] Unable to set custom AUTHENTICATION_TIMEOUT value

### PR DESCRIPTION
**Pull request by lvydra**
https://issues.redhat.com/browse/ELY-1815

### CODE REVIEW

**Comment by lvydra** [comment]
Hi @fjuma @Skyllarr, could I ask you for a review of this PR?

**Comment by ivassile** [comment]
@lvydra Can you please change it to target 2.x branch? Thanks!

**Comment by lvydra** [comment]
Hi @ivassile, the base branch should be 2.x now.

**Review by ivassile — APPROVED** [review]
@Skyllarr LGTM. Can you also review? Thanks!

**Comment by skyllarr** [comment]
@lvydra Can you please rebase this one also? The CI did not run for it yet. If that won't help can you pls try to close it and re-open it ? Otherwise the changes LGTM also

**Comment by lvydra** [comment]
@Skyllarr rebased

**Review by skyllarr — APPROVED** [review]
Thanks @lvydra !

**Pull request merged**
