### PR TITLE
[ELY-2639] Add a test for MaskCommand.decryptMasked method

### PR DESCRIPTION
**Pull request by xjusko**
https://issues.redhat.com/browse/ELY-2639

### CODE REVIEW

**Comment by xjusko** [comment]
Not sure why CI failed, all tests passed on my machine and the tests that failed in CI don't seem to have any connection to my changes.

**Comment by fjuma** [comment]
@xjusko I've re-triggered CI.

**Comment by xjusko** [comment]
Hi @fjuma,  I believe the CI failing has nothing to do with my changes. Could you look at it, please?

**Review by fjuma — APPROVED** [review]
Thanks @xjusko! The changes look good, the failures were indeed unrelated, looks like we might have been hitting an issue with the CI environment. I've re-triggered CI again.

**Review by ivassile — APPROVED** [review]

**Comment by skyllarr** [comment]
Thanks @xjusko !

**Pull request merged**
