### PR TITLE
[ELY-2715] Change log level for ELY23013 and ELY23012 to DEBUG

### PR DESCRIPTION
**Pull request by daspilker**
Change log level for ELY23013 and ELY23012 to DEBUG as suggested by @fjuma.

https://issues.redhat.com/browse/ELY-2715

### CODE REVIEW

**Comment by daspilker** [comment]
I don't think that the CI failures are related to my changes. I rebased the branch, can someone re-trigger the CI?

**Review by fjuma — APPROVED** [review]
Thanks very much @daspilker!

I'm re-triggering CI, the changes look good.

**Comment by fjuma** [comment]
@Skyllarr / @ivassile Please review, thanks!

**Review by ivassile — APPROVED** [review]

**Review by darranl — APPROVED** [review]

**Comment by darranl** [comment]
Thank you @daspilker

**Pull request merged**
