### PR TITLE
[ELY-2555] Upgrade net.minidev:json-smart to 2.4.9

### PR DESCRIPTION
**Pull request by PrarthonaPaul**
https://issues.redhat.com/browse/ELY-2555

### CODE REVIEW

**Comment by fjuma** [comment]
Thanks very much @PrarthonaPaul! Looks good. Just have one small comment. There's an extra file, `elytron-build.log`, that shouldn't be part of the PR. Otherwise looks good!

**Review by fjuma — APPROVED** [review]
Thanks very much @PrarthonaPaul!

**Comment by fjuma** [comment]
@Skyllarr Just FYI, I'm adding the hold label for now since I have the Elytron 2.2.0.Final release in progress. Once I've finished with the release, I'll let you know. Then this one can be merged after.

**Review by skyllarr — APPROVED** [review]

**Comment by skyllarr** [comment]
@PrarthonaPaul Thank you!

**Pull request merged**
