### PR TITLE
[JBEAP-23077] [ELY-2284+ELY-2290] Wildfly OIDC secured App generates a lot of keycloak requests

### PR DESCRIPTION
**Pull request by rmartinc**
Issue: https://issues.redhat.com/browse/JBEAP-23077
Upstream Issue: https://issues.redhat.com/browse/ELY-2284 https://issues.redhat.com/browse/ELY-2290
Upstream PR: https://github.com/wildfly-security/wildfly-elytron/pull/1654 https://github.com/wildfly-security/wildfly-elytron/pull/1660

### CODE REVIEW

**Comment by fjuma** [comment]
@rmartinc If you could also backport the fix from https://github.com/wildfly-security/wildfly-elytron/pull/1660 into this PR, that would be great. Thanks.

**Comment by rmartinc** [comment]
> @rmartinc If you could also backport the fix from #1660 into this PR, that would be great. Thanks.

Done! All tests passed in my env (elytron, core, wildfly and xp-4).

**Comment by fjuma** [comment]
Thanks @rmartinc! Just noticed that we didn't have CI triggering for the 1.15.x branch so I've just enabled that. Whenever you get a chance, if you could rebase this PR, I think that will cause the tests to run. Thanks!

**Comment by rmartinc** [comment]
@fjuma Rebased and tests OK!

**Pull request merged**
