### PR TITLE
[JBEAP-26205] [ELY-2705] Update SecurityDomain#createAdHocIdentity so that it also calls SecurityDomain#transform to ensure that the security domain's security identity transformer gets used if configured

### PR DESCRIPTION
**Pull request by fjuma**
Issue: https://issues.redhat.com/browse/JBEAP-26205
Upstream Issue: https://issues.redhat.com/browse/ELY-2705

### CODE REVIEW

**Review by skyllarr — APPROVED** [review]

**Review by darranl — CHANGES_REQUESTED** [review]
Based on some recent discussions regarding testing I think this would also benefit from a test in the Elytron testsuite that tests this tranformation occurs at the times we expect it to.  Would that make sense @fjuma ?

**Comment by fjuma** [comment]
@darranl Yes, I'll get a test added in the Elytron testsuite for this too.

**Comment by fjuma** [comment]
@darranl @Skyllarr I've now added some tests in the Elytron testsuite for this.

**Review by darranl — APPROVED** [review]

**Comment by darranl** [comment]
Added an approval but it looks like we still need agreement to include for maintenance?

**Comment by fjuma** [comment]
@ivassile Looks like we're still missing acks for this one. Would you be able to help with that? Thanks!

**Comment by istudens** [comment]
@fjuma It's been fully acked. Can it be merged please?

**Comment by skyllarr** [comment]
@istudens I've merged this and so the JBEAP-26205 can be resolved now

**Pull request merged**
