### PR TITLE
[ELY-2729] Upgrade Jackson FasterXML to 2.15.4

### PR DESCRIPTION
**Pull request by darranl**
https://issues.redhat.com/browse/ELY-2729

### CODE REVIEW

**Review by fjuma — APPROVED** [review]
Thanks @darranl

**Review by skyllarr — APPROVED** [review]

**Comment by skyllarr** [comment]
@darranl Just a minor typo in the commit message. Commit says version  2.5.14 but it should be version 2.15.4

**Comment by darranl** [comment]
Thank you @Skyllarr - fixed

**Comment by skyllarr** [comment]
> Thank you @Skyllarr - fixed

@darranl  Just a minor, it says 2.5.4 instead of 2.15.4 now

**Comment by darranl** [comment]
Sorry one more attempt ;-)

**Comment by skyllarr** [comment]
@darranl Thank you!

**Pull request merged**
