### PR TITLE
ELY-2616: Replacing switch statement by if statements to increase readability

### PR DESCRIPTION
**Pull request by srishtih**
https://issues.redhat.com/browse/ELY-2616

### CODE REVIEW

**Comment by PrarthonaPaul** [comment]
LGTM!

**Comment by skyllarr** [comment]
@srishtih This looks great to me! I am approving this PR.

Just btw, it could be simplified even more by using:

return name.equals(SecurityVaultData.PICKETBOX_CLASS_NAME) ?  SecurityVaultData.class : super.resolveClass(desc);

but this looks good as well!

**Review by skyllarr — APPROVED** [review]

**Comment by skyllarr** [comment]
I will just wait for the CI to pass and then I can merge it. Thank you @srishtih !

**Comment by skyllarr** [comment]
Hello @srishtih , just a minor, it is best if you create a separate PR for each issue. This is because the issue ELY-2616 was approved, and then you added changes to this branch, which were not reviewed yet. 

You can create a separate branch for each issue you are working on and then create a separate PR for each branch

**Comment by skyllarr** [comment]
@srishtih Let us know if you need any help with separating this PR into 2 PRs

**Review by skyllarr — APPROVED** [review]

**Comment by skyllarr** [comment]
@srishtih Thank you!

**Comment by PrarthonaPaul** [comment]
LGTM! Thanks @srishtih

**Pull request merged**
