### PR TITLE
[ELY-1211] FileAuditEndpoint doesn't allow for file encoding to be overridden

### PR DESCRIPTION
**Pull request by ivassile**
https://issues.redhat.com/browse/ELY-1211

### CODE REVIEW

**Comment by fjuma** [comment]
Thanks for the PR, @ivassile. My only concern with this is that since the goal is to add a configuration option in the Elytron subsystem to be able to change the file encoding in `FileAuditEndpoint`, this should probably go through the RFE process.

**Comment by ivassile** [comment]
@fjuma I created new issue https://issues.redhat.com/browse/ELY-2018 but don't have permissions to move it to EAP7 project. Can you move it and I'll attach the analysis document? Next, I'll work on implementing the Elytron Subsystem change in Core https://issues.redhat.com/browse/WFCORE-5106.

**Comment by fjuma** [comment]
Sounds good, thanks @ivassile. Moved to to https://issues.redhat.com/browse/EAP7-1557.

**Comment by fjuma** [comment]
Just FYI, I have updated the base branch for this PR to 2.x.

**Comment by fjuma** [comment]
Closing this one since it was superseded by https://github.com/wildfly-security/wildfly-elytron/pull/1900.

**Pull request closed without merging**
