### PR TITLE
[ELY-2664] Upgrade org.apache.httpcomponents:httpclient from 4.5.13 to 4.5.14

### PR DESCRIPTION
**Pull request by Iscar-daniel**
[ELY-2664] Upgrade org.apache.httpcomponents:httpclient from 4.5.13 to 4.5.14
https://issues.redhat.com/browse/ELY-2664?filter=12364234

### CODE REVIEW

**Comment by PrarthonaPaul** [comment]
Hi @Iscar-daniel 
Thank you so much for the PR! 
It seems that your branch has a conflict with the default branch. Could you please resolve it? 
If you have any questions about resolving conflicts, please feel free to let me know.

**Comment by Iscar-daniel** [comment]
Hi @PrarthonaPaul  sure let me fix it

**Comment by PrarthonaPaul** [comment]
Hi @Iscar-daniel 
Thank you for your commit, but the conflict still seems to be there. Could you please rebase again? 
Also, Once you have fixed the conflict, could you please squash all the commits into one with he JIRA issue number and the issue name? Thanks. 
If you need help with squashing commits, please feel free to let me know.

**Comment by Iscar-daniel** [comment]
> Hi @Iscar-daniel Thank you for your commit, but the conflict still seems to be there. Could you please rebase again? Also, Once you have fixed the conflict, could you please squash all the commits into one with he JIRA issue number and the issue name? Thanks. If you need help with squashing commits, please feel free to let me know.

hi @PrarthonaPaul  for the conflicts previously it seems i took wrong approach. now it's fixed. I am try to squash into one commit please notify if me something wrong. thanks

**Comment by skyllarr** [comment]
Hi @Iscar-daniel , just a minor, I can see that this PR contains a change of jakarta.enterprise version, which is unrelated to this ELY-2664 issue. Can you please update this PR to contain only the needed change which is to update only the httpclient version? Thank you!

**Comment by Iscar-daniel** [comment]
> Hi @Iscar-daniel , just a minor, I can see that this PR contains a change of jakarta.enterprise version, which is unrelated to this ELY-2664 issue. Can you please update this PR to contain only the needed change which is to update only the httpclient version? Thank you!

Hi @Skyllarr  I see, thank you for the feedback. updated from my side,

**Comment by skyllarr** [comment]
@Iscar-daniel Just a minor, please remove the superfluous:


`[ELY-2664] Upgrade org.apache.httpcomponents:httpclient https://issues.redhat.com/browse/ELY-2664?filter=-1 Upgrade org.apache.httpcomponents:httpclient from 4.5.13 to 4.5.14 on pom.xml line 70`

from the commit message. Thank you!

**Comment by Iscar-daniel** [comment]
> @Iscar-daniel Just a minor, please remove the superfluous:
> 
> `[ELY-2664] Upgrade org.apache.httpcomponents:httpclient https://issues.redhat.com/browse/ELY-2664?filter=-1 Upgrade org.apache.httpcomponents:httpclient from 4.5.13 to 4.5.14 on pom.xml line 70`
> 
> from the commit message. Thank you!

fixed also

**Review by PrarthonaPaul — APPROVED** [review]
Thanks @Iscar-daniel

**Pull request merged**
