### PR TITLE
[ELY-115] Remove unused DigestHashCallback

### PR DESCRIPTION
**Pull request by dmlloyd**

### CODE REVIEW

**Comment by darranl** [comment]
Just placing on hold for the moment, this is currently used heavily in WildFly and want to be sure we have the same behaviour possible if we remove it.

**Comment by dmlloyd** [comment]
org.jboss.as.domain.http.server.security.RealmIdentityManager and org.jboss.as.security.RealmDirectLoginModule and various callback handlers

**Comment by darranl** [comment]
Still keep this one on-hold, had a slight diversion with key stores and getting back to this area now.

**Comment by darranl** [comment]
@dmlloyd I think moving the mech to use the credential directly is going to be sufficient - if you want to rebase this I will merge.

**Pull request merged**
