### PR TITLE
[ELY-1853] WS integration with WildFly Elytron - AuthenticationClient…

### PR DESCRIPTION
**Pull request by Skyllarr**
… for Authentication / SSL

[ELY-1853](https://issues.jboss.org/browse/ELY-1853) 

Will not compile. Requires jbossws-spi update.

### CODE REVIEW

**Comment by Skyllarr** [comment]
Tests are added now

**Comment by darranl** [comment]
@Skyllarr Following from our discussion this does look like it will also need a rebase, we will also need a good CI run but will need the WS SPI tag to run against.

**Comment by Skyllarr** [comment]
@darranl I rebased on Farah's PR that upgrades client schema version

**Comment by fjuma** [comment]
@Skyllarr Now that this has been pre-checked, we'll need a WS SPI tag before we can merge this one.

**Comment by Skyllarr** [comment]
@fjuma jbossws-spi was tagged as 3.3.0.Final and I updated this branch accordingly.

**Comment by fjuma** [comment]
Thanks @Skyllarr. This looks good, it just needs a conflict to be resolved.

**Comment by Skyllarr** [comment]
@fjuma Thank you. I resolved the conflict.

**Pull request merged**
