### PR TITLE
[ELY-2454] Don't add duplicate value to backed list in MapAttributes

### PR DESCRIPTION
**Pull request by soul2zimate**
issue: https://issues.redhat.com/browse/ELY-2454

### CODE REVIEW

**Comment by fjuma** [comment]
@soul2zimate Thanks for looking into this! After discussing further on the Elytron team call, we realized that we need to be careful about backwards compatibility here since there might be users depending on the existing behaviour. I also just noticed in the PR that we had a test that was depending on the existing behaviour (the test was added here: https://github.com/wildfly-security/wildfly-elytron/pull/584). So this might not be something that we should fix after all.

**Comment by soul2zimate** [comment]
In that case, I can close this PR. However, I was actually redirected from https://github.com/wildfly/wildfly-core/pull/5207,  what's your thought on WFCORE-6052? Is it something we want to fix there ?

**Comment by fjuma** [comment]
@soul2zimate I think the same concerns apply to WFCORE-6052 as well, i.e., there might be users who were depending on the previous behaviour.

**Comment by soul2zimate** [comment]
OK,  I will close the related PR and issue.

**Pull request closed without merging**
