### PR TITLE
[ELY-2182] LogManager warning when using the credential-store command

### PR DESCRIPTION
**Pull request by lvydra**
https://issues.redhat.com/browse/ELY-2182

### CODE REVIEW

**Review by skyllarr — APPROVED** [review]

**Comment by lvydra** [comment]
Hi @fjuma, could I ask you for a review of this PR?

**Comment by fjuma** [comment]
@lvydra Apologies for the delayed review! From the comments in [WFLY-15863](https://issues.redhat.com/browse/WFLY-15863?focusedCommentId=21058613&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-21058613), I'm just wondering if a `jboss-logmanager` component upgrade would fix this instead?

**Comment by lvydra** [comment]
Hi @fjuma, originally I thought so too, but after trying to upgrade the component with no result, I have dug deeper and found out that the system property is not set when LogManager is checking it.

**Comment by fjuma** [comment]
@jamezp Would you be able to take a quick look at this one to see if this is the right way to fix this LogManager warning?

**Review by jamezp — APPROVED** [review]
This seems fine. I think this could also be fixed by upgrading the log manager to 2.1.19.Final. However, being explicit here is fine too.

**Comment by fjuma** [comment]
Thanks @jamezp! @lvydra tried upgrading to 2.1.19.Final instead but that didn't seem to work.

**Comment by jamezp** [comment]
> Thanks @jamezp! @lvydra tried upgrading to 2.1.19.Final instead but that didn't seem to work.

Ah, okay good to know. I'll have a look at that then on the log manager side.

**Comment by jamezp** [comment]
Okay, yes this is the way to do it. I'm not sure it can be fixed in the log manager, so it's best to be explicit here.

**Comment by fjuma** [comment]
Thanks for confirming @jamezp!

**Review by fjuma — APPROVED** [review]
Thanks @lvydra!

**Pull request merged**
