### PR TITLE
[Ely 584] used methods, AuthenticationConfiguration.EMPTY is flaged as deprecated

### PR DESCRIPTION
**Pull request by 9788072178346**
Added method empty() for AuthenticationConfiguration to make things consistent.

### CODE REVIEW

**Comment by kabir** [comment]
We require that all contributions be made under the terms of the MIT License, http://www.opensource.org/licenses/mit-license.php. Do you agree to the these terms?

**Comment by kabir** [comment]
Would you be able to update either your profile or reply here with your name, so we know who this is coming from? We need this for our records :)

**Comment by darranl** [comment]
This is OK to test.

**Comment by 9788072178346** [comment]
I agree.

(Sure, I'm gonna go fill out the profile right now :) )

**Comment by 9788072178346** [comment]
Works now.

**Comment by dmlloyd** [comment]
This is OK to test

**Comment by honza889** [comment]
Changes requested by @darranl : as a later API change there is a big risk that it could affect WildFly Core and WildFly and any clients we don't know about that may have used the field.  It would be safer **to leave the field public but flag it as deprecated**.

**Comment by ctomc** [comment]
this is ok to test

**Pull request merged**
