### PR TITLE
ELY-2778 Replace string literals inside the OidcJsonConfiguration class with constants

### PR DESCRIPTION
**Pull request by PrarthonaPaul**
Issue: https://issues.redhat.com/browse/ELY-2778

### CODE REVIEW

**Review by ivassile — CHANGES_REQUESTED** [review]
@PrarthonaPaul You have to change the tests to also use the new constants.

**Comment by PrarthonaPaul** [comment]
> @PrarthonaPaul You have to change the tests to also use the new constants.

Thanks @ivassile 
I have edited the tests to use the constants.

**Comment by fjuma** [comment]
This one will need a rebase now.

**Review by ivassile — APPROVED** [review]

**Comment by PrarthonaPaul** [comment]
> This one will need a rebase now.

Hi @fjuma This PR is good to go now

**Review by darranl — APPROVED** [review]

**Pull request merged**
