### PR TITLE
Don't merge - investigation of failing CommandCredentialSourceTest in Travis CI

### PR DESCRIPTION
**Pull request by kwart**
# Don't merge
Just trying Travis CI with isolated failing test.

### CODE REVIEW

**Comment by kwart** [comment]
First (passing) build was with java version "1.8.0_131" - https://travis-ci.org/wildfly-security/wildfly-elytron/builds/274517329

**Comment by kwart** [comment]
Second (failing) build was with java version "1.8.0_144" - https://travis-ci.org/wildfly-security/wildfly-elytron/builds/274518947

**Comment by kwart** [comment]
The java process used to retrieve the password credential exits with code `141`. Does anybody know what does it mean?

```
[INFO] Running org.wildfly.security.credential.source.CommandCredentialSourceTest
java.home=/usr/lib/jvm/java-8-oracle/jre
java.class.path=/home/travis/build/wildfly-security/wildfly-elytron/target/test-classes:/home/travis/build/wildfly-security/wildfly-elytron/target/classes:/home/travis/.m2/repository/org/jboss/logging/jboss-logging/3.3.1.Final/jboss-logging-3.3.1.Final.jar:/home/travis/.m2/repository/org/jboss/logging/jboss-logging-annotations/2.0.1.Final/jboss-logging-annotations-2.0.1.Final.jar:/home/travis/.m2/repository/org/jboss/logging/jboss-logging-processor/2.0.1.Final/jboss-logging-processor-2.0.1.Final.jar:/home/travis/.m2/repository/org/jboss/jdeparser/jdeparser/2.0.0.Final/jdeparser-2.0.0.Final.jar:/home/travis/.m2/repository/org/jboss/logmanager/jboss-logmanager/2.0.6.Final/jboss-logmanager-2.0.6.Final.jar:/home/travis/.m2/repository/org/jboss/modules/jboss-modules/1.6.0.Final/jboss-modules-1.6.0.Final.jar:/home/travis/.m2/repository/org/kohsuke/metainf-services/metainf-services/1.7/metainf-services-1.7.jar:/home/travis/.m2/repository/org/wildfly/client/wildfly-client-config/1.0.0.Final/wildfly-client-config-1.0.0.Final.jar:/home/travis/.m2/repository/org/wildfly/common/wildfly-common/1.2.0.Final/wildfly-common-1.2.0.Final.jar:/home/travis/.m2/repository/org/jboss/spec/javax/security/jacc/jboss-jacc-api_1.5_spec/1.0.1.Final/jboss-jacc-api_1.5_spec-1.0.1.Final.jar:/home/travis/.m2/repository/org/jboss/spec/javax/servlet/jboss-servlet-api_3.1_spec/1.0.0.Final/jboss-servlet-api_3.1_spec-1.0.0.Final.jar:/home/travis/.m2/repository/org/jboss/spec/javax/json/jboss-json-api_1.0_spec/1.0.0.Final/jboss-json-api_1.0_spec-1.0.0.Final.jar:/home/travis/.m2/repository/org/jboss/threads/jboss-threads/2.2.1.Final/jboss-threads-2.2.1.Final.jar:/home/travis/.m2/repository/org/apache/directory/api/api-asn1-api/1.0.0-M23/api-asn1-api-1.0.0-M23.jar:/home/travis/.m2/repository/org/apache/directory/api/api-i18n/1.0.0-M23/api-i18n-1.0.0-M23.jar:/home/travis/.m2/repository/org/slf4j/slf4j-api/1.7.7/slf4j-api-1.7.7.jar:/home/travis/.m2/repository/org/apache/directory/api/api-asn1-ber/1.0.0-M23/api-asn1-ber-1.0.0-M23.jar:/home/travis/.m2/repository/org/apache/directory/api/api-util/1.0.0-M23/api-util-1.0.0-M23.jar:/home/travis/.m2/repository/org/apache/directory/api/api-ldap-codec-core/1.0.0-M23/api-ldap-codec-core-1.0.0-M23.jar:/home/travis/.m2/repository/org/apache/mina/mina-core/2.0.7/mina-core-2.0.7.jar:/home/travis/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar:/home/travis/.m2/repository/commons-collections/commons-collections/3.2.1/commons-collections-3.2.1.jar:/home/travis/.m2/repository/org/apache/directory/api/api-ldap-codec-standalone/1.0.0-M23/api-ldap-codec-standalone-1.0.0-M23.jar:/home/travis/.m2/repository/org/apache/directory/api/api-ldap-net-mina/1.0.0-M23/api-ldap-net-mina-1.0.0-M23.jar:/home/travis/.m2/repository/org/apache/directory/api/api-ldap-extras-codec/1.0.0-M23/api-ldap-extras-codec-1.0.0-M23.jar:/home/travis/.m2/repository/org/apache/directory/api/api-ldap-extras-codec-api/1.0.0-M23/api-ldap-extras-codec-api-1.0.0-M23.jar:/home/travis/.m2/repository/org/apache/directory/api/api-ldap-model/1.0.0-M23/api-ldap-model-1.0.0-M23.jar:/home/travis/.m2/repository/antlr/antlr/2.7.7/antlr-2.7.7.jar:/home/travis/.m2/repository/org/apache/directory/jdbm/apacheds-jdbm1/2.0.0-M2/apacheds-jdbm1-2.0.0-M2.jar:/home/travis/.m2/repository/org/apache/directory/server/apacheds-core-api/2.0.0-M17/apacheds-core-api-2.0.0-M17.jar:/home/travis/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar:/home/travis/.m2/repository/org/apache/directory/server/apacheds-core-constants/2.0.0-M17/apacheds-core-constants-2.0.0-M17.jar:/home/travis/.m2/repository/org/apache/directory/server/apacheds-i18n/2.0.0-M17/apacheds-i18n-2.0.0-M17.jar:/home/travis/.m2/repository/org/apache/directory/api/api-ldap-client-api/1.0.0-M23/api-ldap-client-api-1.0.0-M23.jar:/home/travis/.m2/repository/commons-pool/commons-pool/1.6/commons-pool-1.6.jar:/home/travis/.m2/repository/org/apache/directory/api/api-ldap-extras-aci/1.0.0-M23/api-ldap-extras-aci-1.0.0-M23.jar:/home/travis/.m2/repository/org/apache/directory/api/api-ldap-extras-util/1.0.0-M23/api-ldap-extras-util-1.0.0-M23.jar:/home/travis/.m2/repository/org/apache/directory/api/api-ldap-schema-data/1.0.0-M23/api-ldap-schema-data-1.0.0-M23.jar:/home/travis/.m2/repository/net/sf/ehcache/ehcache-core/2.4.4/ehcache-core-2.4.4.jar:/home/travis/.m2/repository/org/apache/directory/server/apacheds-core-annotations/2.0.0-M17/apacheds-core-annotations-2.0.0-M17.jar:/home/travis/.m2/repository/org/apache/directory/server/apacheds-core/2.0.0-M17/apacheds-core-2.0.0-M17.jar:/home/travis/.m2/repository/org/apache/directory/server/apacheds-interceptors-admin/2.0.0-M17/apacheds-interceptors-admin-2.0.0-M17.jar:/home/travis/.m2/repository/org/apache/directory/server/apacheds-interceptors-authn/2.0.0-M17/apacheds-interceptors-authn-2.0.0-M17.jar:/home/travis/.m2/repository/org/apache/directory/server/apacheds-interceptors-number/2.0.0-M17/apacheds-interceptors-number-2.0.0-M17.jar:/home/travis/.m2/repository/org/apache/directory/server/apacheds-interceptors-authz/2.0.0-M17/apacheds-interceptors-authz-2.0.0-M17.jar:/home/travis/.m2/repository/org/apache/directory/server/apacheds-interceptors-changelog/2.0.0-M17/apacheds-interceptors-changelog-2.0.0-M17.jar:/home/travis/.m2/repository/org/apache/directory/server/apacheds-interceptors-collective/2.0.0-M17/apacheds-interceptors-collective-2.0.0-M17.jar:/home/travis/.m2/repository/org/apache/directory/server/apacheds-interceptors-event/2.0.0-M17/apacheds-interceptors-event-2.0.0-M17.jar:/home/travis/.m2/repository/org/apache/directory/server/apacheds-interceptors-exception/2.0.0-M17/apacheds-interceptors-exception-2.0.0-M17.jar:/home/travis/.m2/repository/org/apache/directory/server/apacheds-interceptors-journal/2.0.0-M17/apacheds-interceptors-journal-2.0.0-M17.jar:/home/travis/.m2/repository/org/apache/directory/server/apacheds-interceptors-normalization/2.0.0-M17/apacheds-interceptors-normalization-2.0.0-M17.jar:/home/travis/.m2/repository/org/apache/directory/server/apacheds-interceptors-operational/2.0.0-M17/apacheds-interceptors-operational-2.0.0-M17.jar:/home/travis/.m2/repository/org/apache/directory/server/apacheds-interceptors-referral/2.0.0-M17/apacheds-interceptors-referral-2.0.0-M17.jar:/home/travis/.m2/repository/org/apache/directory/server/apacheds-interceptors-schema/2.0.0-M17/apacheds-interceptors-schema-2.0.0-M17.jar:/home/travis/.m2/repository/org/apache/directory/server/apacheds-interceptors-subtree/2.0.0-M17/apacheds-interceptors-subtree-2.0.0-M17.jar:/home/travis/.m2/repository/org/apache/directory/server/apacheds-interceptors-trigger/2.0.0-M17/apacheds-interceptors-trigger-2.0.0-M17.jar:/home/travis/.m2/repository/org/apache/directory/api/api-ldap-extras-trigger/1.0.0-M23/api-ldap-extras-trigger-1.0.0-M23.jar:/home/travis/.m2/repository/org/apache/directory/server/apacheds-core-shared/2.0.0-M17/apacheds-core-shared-2.0.0-M17.jar:/home/travis/.m2/repository/org/apache/directory/server/apacheds-ldif-partition/2.0.0-M17/apacheds-ldif-partition-2.0.0-M17.jar:/home/travis/.m2/repository/org/apache/directory/server/apacheds-jdbm-partition/2.0.0-M17/apacheds-jdbm-partition-2.0.0-M17.jar:/home/travis/.m2/repository/org/apache/directory/server/apacheds-core-avl/2.0.0-M17/apacheds-core-avl-2.0.0-M17.jar:/home/travis/.m2/repository/org/apache/directory/server/apacheds-xdbm-partition/2.0.0-M17/apacheds-xdbm-partition-2.0.0-M17.jar:/home/travis/.m2/repository/org/apache/directory/server/apacheds-mavibot-partition/2.0.0-M17/apacheds-mavibot-partition-2.0.0-M17.jar:/home/travis/.m2/repository/org/apache/directory/server/apacheds-interceptor-kerberos/2.0.0-M17/apacheds-interceptor-kerberos-2.0.0-M17.jar:/home/travis/.m2/repository/org/apache/directory/server/apacheds-kerberos-codec/2.0.0-M17/apacheds-kerberos-codec-2.0.0-M17.jar:/home/travis/.m2/repository/org/apache/directory/server/apacheds-protocol-kerberos/2.0.0-M17/apacheds-protocol-kerberos-2.0.0-M17.jar:/home/travis/.m2/repository/org/apache/directory/server/apacheds-protocol-shared/2.0.0-M17/apacheds-protocol-shared-2.0.0-M17.jar:/home/travis/.m2/repository/org/apache/directory/server/apacheds-protocol-ldap/2.0.0-M17/apacheds-protocol-ldap-2.0.0-M17.jar:/home/travis/.m2/repository/org/apache/directory/api/api-ldap-extras-sp/1.0.0-M23/api-ldap-extras-sp-1.0.0-M23.jar:/home/travis/.m2/repository/bouncycastle/bcprov-jdk15/140/bcprov-jdk15-140.jar:/home/travis/.m2/repository/org/apache/directory/mavibot/mavibot/1.0.0-M5/mavibot-1.0.0-M5.jar:/home/travis/.m2/repository/org/jboss/logmanager/log4j-jboss-logmanager/1.1.4.Final/log4j-jboss-logmanager-1.1.4.Final.jar:/home/travis/.m2/repository/org/jboss/slf4j/slf4j-jboss-logmanager/1.0.3.GA/slf4j-jboss-logmanager-1.0.3.GA.jar:/home/travis/.m2/repository/junit/junit/4.12/junit-4.12.jar:/home/travis/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/home/travis/.m2/repository/org/jmockit/jmockit/1.33/jmockit-1.33.jar:/home/travis/.m2/repository/org/hsqldb/hsqldb/2.4.0/hsqldb-2.4.0.jar:/home/travis/.m2/repository/org/glassfish/javax.json/1.0.4/javax.json-1.0.4.jar:/home/travis/.m2/repository/com/nimbusds/nimbus-jose-jwt/4.39.2/nimbus-jose-jwt-4.39.2.jar:/home/travis/.m2/repository/com/github/stephenc/jcip/jcip-annotations/1.0-1/jcip-annotations-1.0-1.jar:/home/travis/.m2/repository/net/minidev/json-smart/2.3/json-smart-2.3.jar:/home/travis/.m2/repository/net/minidev/accessors-smart/1.2/accessors-smart-1.2.jar:/home/travis/.m2/repository/org/ow2/asm/asm/5.0.4/asm-5.0.4.jar:/home/travis/.m2/repository/com/squareup/okhttp3/mockwebserver/3.8.1/mockwebserver-3.8.1.jar:/home/travis/.m2/repository/com/squareup/okhttp3/okhttp/3.8.1/okhttp-3.8.1.jar:/home/travis/.m2/repository/com/squareup/okio/okio/1.13.0/okio-1.13.0.jar:/home/travis/.m2/repository/org/bouncycastle/bcprov-jdk15on/1.50/bcprov-jdk15on-1.50.jar:
java exists=true
java isFile=true
java.exe exists=false
java.exe isFile=false
Command output = null
11:30:29,201 TRACE (main) [org.wildfly.security] <CommandCredentialSource.java:114> Exit code from password command = 141
Exit code from password command = 141
```

**Comment by kwart** [comment]
It seems that closing the error stream causes the problem:
```
Command output stdOut=secret_key_THREE
Command output stdErr=Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m
07:50:32,809 TRACE (main) [org.wildfly.security] <CommandCredentialSource.java:138> Exit code from password command = 0
Exit code from password command = 0
```
https://travis-ci.org/wildfly-security/wildfly-elytron/builds/274931279

**Comment by hsvabek** [comment]
You can reproduce it locally:
You must set _JAVA_OPTIONS env variable

export _JAVA_OPTIONS='-Xmx2048m -Xms512m'
mvn clean package -Dtest=CommandCredentialSourceTest

**Comment by kwart** [comment]
Closing as the investigation is done. The issue reported in https://issues.jboss.org/browse/JBEAP-13145

**Pull request closed without merging**
