### PR TITLE
[ELY-2815] Renamed CA_JKS_LOCATION to CA_PKCS_LOCATION in TLS13AuthenticationTest

### PR DESCRIPTION
**Pull request by luisa-ball**
https://issues.redhat.com/browse/ELY-2815

### CODE REVIEW

**Review by fjuma — APPROVED** [review]
Looks great! Thanks very much @luisa-ball!

**Review by SoniaZaldana — APPROVED** [review]
Looks good to me :)

**Review by luck3y — APPROVED** [review]

**Comment by rsearls** [comment]
1+ reviewed.  Looks good

**Comment by SoniaZaldana** [comment]
Hi @luisa-ball, we haven't yet merged this PR. Could you reopen it?

**Comment by luisa-ball** [comment]
Hi, sorry! I was having issues with my GitHub I will send the PR again.

**Pull request closed without merging**
