### PR TITLE
ELY-1299 X509EvidenceVerificationSuiteChild.testX509Auth() fails on IBM

### PR DESCRIPTION
**Pull request by ppalaga**
https://issues.jboss.org/browse/ELY-1299

Note that there are more `*.pem` files with non-PEM content there in `src/test/resources/ca/certs`. Changing those has not brought any change on IBM JDK. Hence left them untouched.

### CODE REVIEW

**Comment by honza889** [comment]
Parsing PEM files with text prefix should be handled by https://github.com/wildfly-security/wildfly-elytron/blob/master/src/main/java/org/wildfly/security/pem/Pem.java#L74 - maybe should be fixed here...

**Comment by ppalaga** [comment]
> Parsing PEM files with text prefix should be handled by https://github.com/wildfly-security/wildfly-elytron/blob/master/src/main/java/org/wildfly/security/pem/Pem.java#L74 (but it obviously doesnt work when - in text prefix) - maybe should be fixed here... (and to use it for certificate loading in test)

@honza889 `X509EvidenceVerificationSuiteChild.testX509Auth()` does not use `Pem`. It uses `CertificateFactory.getInstance("X.509").generateCertificate(is)` directly. I have filed a separate issue for the `Pem` class https://issues.jboss.org/browse/ELY-1300

**Comment by ppalaga** [comment]
@honza889 ... and https://issues.jboss.org/browse/ELY-1301 too

**Comment by darranl** [comment]
We have the certificate in a JKS KeyStore, instead of loading from the pem (which is not really what is being tested at the time of the failure) why not load directly from the JKS KeyStore?

**Comment by ppalaga** [comment]
> We have the certificate in a JKS KeyStore, instead of loading from the pem (which is not really what is being tested at the time of the failure) why not load directly from the JKS KeyStore?

Accepted in ec8b9e9

**Comment by darranl** [comment]
Thanks, will just wait for CI to finish then this can be merged.

**Pull request merged**
