### PR TITLE
DO NOT MERGE YET (Review only) [ELY-1459] Use WildFly Common byte and code point iterators

### PR DESCRIPTION
**Pull request by dmlloyd**

### CODE REVIEW

**Comment by darranl** [comment]
Just to confirm I have double checked the classes we advertise as public API, none of the removed classes have been flagged as public API so we are safe to remove without deprecation.

**Comment by darranl** [comment]
Just trying to read between the lines of some concurrent changes - we know moving is safe as these are not currently supported.

@fjuma Combined with the changes you are also working on do we need the end result for these classes to be that they are supported or not supported?

**Comment by dmlloyd** [comment]
Just wanted to make a note that we cannot include a release with this change into WildFly until the few usages of this API therein are removed, which must happen _after_ the final release of wildfly-common.  So there's a dependency chain here.

**Comment by fjuma** [comment]
@darranl The end result should be that these classes are supported in wildfly-common.

**Comment by darranl** [comment]
At the moment the org.wildfly.common module is flagged as private.  @dmlloyd Is that something that could change?

Regarding the .Final tag, we already have .Beta releases of WildFly Elytron in WildFly Core master - do we strictly need to depend on a .Final?

**Comment by dmlloyd** [comment]
I'm not opposed to making it public, but my vote doesn't really count on that score.

**Comment by fjuma** [comment]
This is now superseded by #1078, which resolves the conflicts. Closing this one.

**Pull request closed without merging**
