### PR TITLE
[ELY-1550] FileAuditEndpoint - independent flush/sync

### PR DESCRIPTION
**Pull request by hkalina**
Allowed to enable/disable flush/sync independently.

Related subsystem change: https://github.com/wildfly/wildfly-core/pull/3186

https://issues.jboss.org/browse/ELY-1550
https://issues.jboss.org/browse/JBEAP-10639

### CODE REVIEW

**Comment by darranl** [comment]
I have approved and placed on hold just so we can ensure the correct coordination is in place before the merge.

**Comment by hkalina** [comment]
@darranl core PR should be ok now: https://github.com/wildfly/wildfly-core/pull/3186

**Comment by darranl** [comment]
Thanks @hkalina 

@fjuma Did you want to double check you still agree with your +1?

**Comment by fjuma** [comment]
Looks good.

**Pull request merged**
