### PR TITLE
Adding tests for CipherSuiteSelector

### PR DESCRIPTION
**Pull request by OndrejKotek**

### CODE REVIEW

**Comment by darranl** [comment]
What is the different between this new class and org.wildfly.security.ssl.MechanismDatabaseTest ? Could all these tests be merged into one class?

**Comment by OndrejKotek** [comment]
MechanismDatabaseTest contains test for MechanismDatabase and few tests for CipherSuiteSelector. The new class covers basic functionality of CipherSuiteSelector systematically. Should I move the CipherSuiteSelector tests from the MechanismDatabaseTest to the new class?

**Comment by darranl** [comment]
Yes, if you could please move those tests over to your new class - it will make it easier in future if we have them in a single location.  As you are moving existing code I would suggest perform the move in a new commit so the history is clear.

**Comment by OndrejKotek** [comment]
Moved.

**Pull request merged**
