### PR TITLE
Merge branch '1.15.x' into 1.19.x

### PR DESCRIPTION
**Pull request by boris-unckel**
Utilize latest released version to maintain 1.19.x

### CODE REVIEW

**Comment by boris-unckel** [comment]
@Skyllarr @fjuma Could you check this, please? Is this the correct approach to maintain a version?

**Comment by fjuma** [comment]
Hi @boris-unckel, we actually handle forward porting fixes to active branches as part of our maintenance release process. So when we fix something on an active maintenance branch like 1.15.x, when we do the release, we forward port the fixes to the rest of the active branches (e.g., 1.x and 2.x). 

The 1.19.x Elytron branch was used for WildFly 26.x. However, we don't plan on having more WildFly 26.x releases so the 1.19.x branch is no longer active.

**Comment by fjuma** [comment]
If you do need to use the 1.19.x branch though, we can forward port the changes.

**Comment by boris-unckel** [comment]
@fjuma I'm very happy about everything I can get out of the box in our downstream fork. If its possible a forward port would be great.

**Comment by fjuma** [comment]
Sure thing, @boris-unckel, I've forward ported the changes from the 1.15.x branch to the 1.19.x branch. I'll close this PR now.

**Pull request closed without merging**
