### PR TITLE
[ELY-2667] Upgrade org.jboss.logging:jboss-logging from 3.4.3.Final to 3.5.3.Final

### PR DESCRIPTION
**Pull request by Iscar-daniel**
[ELY-2667] Upgrade org.jboss.logging:jboss-logging from 3.4.3.Final to 3.5.3.Final
https://issues.redhat.com/browse/ELY-2667?filter=12364234

### CODE REVIEW

**Comment by skyllarr** [comment]
HI @Iscar-daniel , please update the commit message to contain the issue number ELY-2667 at the beginning. Thank you!

**Review by skyllarr — APPROVED** [review]
Thanks @Iscar-daniel  !

**Comment by PrarthonaPaul** [comment]
Hi @Iscar-daniel 
It seems like the commit message has an extra `ELY-2667] Upgrade org.jboss.logging:jboss-logging from 3.4.3.Final to 3.5.3.Final https://issues.redhat.com/browse/ELY-2667?filter=12364234` added to it. Could you please edit the commit message to fix it? Also, this is minor, but could you also add the `[` to the beginning of the commit message? Thanks

**Comment by Iscar-daniel** [comment]
> Hi @Iscar-daniel It seems like the commit message has an extra `ELY-2667] Upgrade org.jboss.logging:jboss-logging from 3.4.3.Final to 3.5.3.Final https://issues.redhat.com/browse/ELY-2667?filter=12364234` added to it. Could you please edit the commit message to fix it? Also, this is minor, but could you also add the `[` to the beginning of the commit message? Thanks

i see, i just added the summary is that ok?  the '[' character is added

**Review by fjuma — APPROVED** [review]
Looks good, thanks @Iscar-daniel and welcome to the WildFly Elytron project!

**Pull request merged**
