### PR TITLE
Introduce an abstraction for supporting an association between a secu…

### PR DESCRIPTION
**Pull request by dmlloyd**
…rity domain and a SASL server factory

### CODE REVIEW

**Comment by dmlloyd** [comment]
Consumers of SASL server factories (SSFs) often have need to wrap the SSF for their own purposes, for example to support channel binding, SSL external authentication, and providing auxiliary information to the authentication process such as local and peer IP address.  Thus we cannot wrap the SSF; we must instead simply abstract the association of a security domain with a pre-configured SSF, and thereby provide the protocol implementation the opportunity to acquire and wrap this SSF before passing it back in to the ServerAuthenticationContext for construction of the final SASL server.

The subsystem would provide a ``SecurityDomainSaslConfiguration`` which would hold the pre-configured SASL server factory as well as the security domain against which it is to authenticate.

**Comment by honza889** [comment]
Maybe should be made same simplification of `sasl.util.AbstractSasl*`

**Comment by dmlloyd** [comment]
In what way?

**Comment by honza889** [comment]
Moving serverName/protocol factory arguments into props. 
Hm, I have forgotten SaslServerFactory is part of JDKs interface - please ignore this note.

**Comment by dmlloyd** [comment]
This can be reviewed but I want to wait until @darranl gets back before merging, because this is targeted specifically to him.

**Pull request merged**
