### PR TITLE
[ELY-1876] Log messages are not logged when KeyStoreCredentialStore is initialized with Provider[] in getKeyStoreInstance.

### PR DESCRIPTION
**Pull request by ivassile**
https://issues.jboss.org/browse/ELY-1876

### CODE REVIEW

**Comment by darranl** [comment]
This one needs submitting either against the 1.x branch or if this is for a maintenance release it should be against the 1.6.x branch.

**Comment by ivassile** [comment]
@darranl This is not for maintenance release. Can you explain why submitting to 1.x? Is it master the Elytron upstream branch?

**Comment by darranl** [comment]
master is for Elytron 2.0.0 which is not scheduled to be included in any WildFly releases for the foreseeable future - the releases for WildFly are being tagged from the 1.x branch.

**Comment by ivassile** [comment]
Thanks for the clarification. New PR https://github.com/wildfly-security/wildfly-elytron/pull/1329

**Pull request closed without merging**
