### PR TITLE
[ELY-1660] / [ELY-1642] / [ELY-1654] Converting to multi-release jar from JDK 9 onwards.

### PR DESCRIPTION
**Pull request by darranl**

### CODE REVIEW

**Comment by luck3y** [comment]
retest this please

**Comment by luck3y** [comment]
retest this please

**Comment by luck3y** [comment]
retest this please

**Comment by darranl** [comment]
Changes approved under: -
https://github.com/wildfly-security/wildfly-elytron/pull/1182
https://github.com/wildfly-security/wildfly-elytron/pull/1181

**Pull request merged**
