### PR TITLE
[ELY-2101] Upgrade Apache sshd-common to a version that depends on slf4j 1.7.30

### PR DESCRIPTION
**Pull request by SoniaZaldana**
https://issues.redhat.com/browse/ELY-2101

### CODE REVIEW

**Comment by fjuma** [comment]
Just temporarily adding the Hold label as Sonia is just double checking some test failures in Core that occur with sshd-common version 2.6.0.

**Review by fjuma — APPROVED** [review]

**Comment by Skyllarr** [comment]
@SoniaZaldana this just needs a rebase if you'll have time

**Comment by fjuma** [comment]
Just FYI, I have updated the base branch for this PR to 2.x.

**Comment by fjuma** [comment]
Closing this one since this PR is now out of date (2.x is already on sshd-common 2.10.0).

**Pull request closed without merging**
