### PR TITLE
[ELY-2688] Merge an if statement with the enclosing one 

### PR DESCRIPTION
**Pull request by gabrielpadilh4**
Merge an if statement with the enclosing one in RequestAuthenticator#authenticate

https://issues.redhat.com/browse/ELY-2688

### CODE REVIEW

**Comment by PrarthonaPaul** [comment]
Hi @gabrielpadilh4 
Thank you for your PR! 
I noticed on your first commit, it mentions "fjuma authored and gabrielpadilh4 committed" Could you please look into it to check if you accidentally amended it with another commit? It seems that the changes you reverted are related to this issue: https://issues.redhat.com/browse/ELY-2695
Once you figure that out, could you also squash your commits into a single commit? Thank you!

**Comment by gabrielpadilh4** [comment]
Hi @PrarthonaPaul , i fixed the commit, could you please review it again ? Thank you.

**Comment by PrarthonaPaul** [comment]
Hi @gabrielpadilh4 
Thank you for taking a look. 
It seems that your commit is still connected to the previous commit (Perhaps a merge commit?) So, it still says "fjuma authored and gabrielpadilh4 committed". Would you be able to undo that? Thank you!

**Comment by gabrielpadilh4** [comment]
Hello @PrarthonaPaul i think i was able to add only the file that should be changed.
Can you take a look now ?

**Review by PrarthonaPaul — APPROVED** [review]
LGTM! Thank you @gabrielpadilh4

**Review by fjuma — APPROVED** [review]
Thanks @gabrielpadilh4!

**Review by skyllarr — APPROVED** [review]

**Pull request merged**
