### PR TITLE
ELY-2308: Fix digest authentication for requests with encoded path parameters

### PR DESCRIPTION
**Pull request by gjaekel**
As for the query part, for the path part also use the raw representation.

Fixes #1675 (https://issues.redhat.com/browse/ELY-2308)

### CODE REVIEW

**Comment by fjuma** [comment]
Thanks for the PR, @gjaekel!

If you could update the commit message to also reference ELY-2308 that would be great. Thanks.

**Comment by skyllarr** [comment]
Hello @gjaekel , I submitted [another PR ](https://github.com/wildfly-security/wildfly-elytron/pull/1682)with your changes and updated the commit message.

**Comment by fjuma** [comment]
Superseded by https://github.com/wildfly-security/wildfly-elytron/pull/1682. Thanks @gjaekel and @Skyllarr!

**Comment by gjaekel** [comment]
Hello @Skyllarr, thank you for support! But you "solved" the one problem by kicking me out and rise another by opening an new, unfilled [JIRA Issue](https://issues.redhat.com/browse/ELY-2315). Don't know if that was the thought of @fjuma .

**Comment by fjuma** [comment]
@gjaekel There isn't a way for us to modify your branch without creating a new PR. Since you wanted us to amend the commit, I asked @Skyllarr to take care of it. She cherry-picked the commit directly from your branch though so you still appear as the author of the commit. :)

Since the original JIRA issue (ELY-2038) was already resolved, I also asked @Skyllarr to create a new JIRA issue for this follow-up change since she was tweaking the commit message anyway so could easily reference the new issue.

Thanks.

**Comment by gjaekel** [comment]
No problem with this at all! Most important is that we have fixed this regression. 

Thank you for your support and pre-work. I was pointed to this Issue because it seems to fit my own observations. But the suggested patch don't fix it. I'm not working as developer, but I'm a physicist: Just from staring at the code, I notice the "symmetry violation" of the patch and correcting this solves the things at once ...

**Comment by skyllarr** [comment]
@gjaekel I see, thanks a lot for noticing that and for the fix!

**Pull request closed without merging**
