### PR TITLE
[ELY-990] Simplify and correct server-side credential acquisition

### PR DESCRIPTION
**Pull request by dmlloyd**

### CODE REVIEW

**Comment by darranl** [comment]
Adding both a ~1 and a "Hold" as this will break the subsystem which means it will also break WildFly Core if the subsystem is merged into it 

Will coordinate some changes to WildFly Core.

**Comment by dmlloyd** [comment]
IIRC this was meant to be backwards compatible... what did it break?

**Comment by darranl** [comment]
Ah maybe not broken, I see the setSecurityFactory method is still there.

Do we really want to retain that though?

**Comment by dmlloyd** [comment]
For now anyway :)

**Pull request merged**
