### PR TITLE
Website update for OSD 2024

### PR DESCRIPTION
**Pull request by PrarthonaPaul**
Preview: https://prarthonapaul.github.io/wildfly-elytron/OSD/
hacktoberfest preview: https://prarthonapaul.github.io/wildfly-elytron/hacktoberfest/

TODO for OSD: 
If a banner for OSD2024 is available, that should be added

TODO for hacktoberfest:
add a banner for this year inside assets/images/posts/ once it is available.
Confirm this: You’ll have the option to have a tree planted in your name and you can obtain a unique digital reward. Visit the [Hacktoberfest site](https://hacktoberfest.com/participation/) for more information.

Small update is added to fix the header for blog page.

### CODE REVIEW

**Comment by fjuma** [comment]
@PrarthonaPaul Feel free to include the hacktoberfest commit in this one too so both can be previewed and merged together. 

Just noticed the OSD image is quite large and a bit blurry.

If we can't make that smaller, we could just remove the graphic for now or maybe just use a standard generic GHC logo instead?

**Comment by PrarthonaPaul** [comment]
Hi @fjuma 
I got rid of the picture for the banner, but still kept it for the metadata, so when the link is shared, this picture would show up. Like this: 
image

And I have added the hacktoberfest commit here as well.

**Comment by fjuma** [comment]
Is it possible to have buttons for "Open Source Day" and "Hacktoberfest" appear at the top of the homepage? Right now, I just see "OSD 2024"

**Comment by PrarthonaPaul** [comment]
> Is it possible to have buttons for "OSD" and "Hacktoberfest" appear at the top of the homepage?

Done! 
https://prarthonapaul.github.io/wildfly-elytron/
The homepage still does say "[Welcome new Open Source Day participants! Click here to get started!](https://prarthonapaul.github.io/wildfly-elytron/OSD/)". 

Should I add one for hacktoberfest as well? or leave it as is?

**Comment by fjuma** [comment]
Just some small nits:

* Let's rename "OSD 2024" to "Open Source Day"
* Can we put that before Hacktoberfest?
* Is it possible to introduce some spacing between the buttons?

We can leave the welcome message as is so it stands out for the Open Source Day participants.

**Comment by PrarthonaPaul** [comment]
Hi @fjuma 
done! Preview can be found here: https://prarthonapaul.github.io/wildfly-elytron/
The space between the buttons might take a while to show up.

**Review by fjuma — APPROVED** [review]

**Pull request merged**
