### PR TITLE
[ELY-2392] Fix invalid tags on the Elytron Blogs page

### PR DESCRIPTION
**Pull request by Tanya-11**
https://issues.redhat.com/browse/ELY-2392

### CODE REVIEW

**Comment by skyllarr** [comment]
Hello @Tanya-11 , thank you for the PR! As part of this task, we should also remove usages of the tags with comma from the existing posts. For example the following post:

https://github.com/wildfly-security/wildfly-elytron/blob/develop/_posts/2022-04-19-improving-readability-of-alias-commands.adoc

should have tags adjusted

**Comment by fjuma** [comment]
Thanks for the PR @Tanya-11!

@Skyllarr Looks like the changes in this PR update the file you mentioned. Was there something else you noticed?

**Comment by skyllarr** [comment]
@fjuma Nope, it is just in this file. Sorry I misread the name of the file in this PR. Approving

**Review by skyllarr — APPROVED** [review]

**Comment by Tanya-11** [comment]
@fjuma, Can you pls review this PR? Thanks

**Review by fjuma — APPROVED** [review]

**Pull request merged**
