### PR TITLE
[ELY-2547] Add Elytron Tool option to overwrite CLI script

### PR DESCRIPTION
**Pull request by darranl**
Re-apply the changes for https://issues.redhat.com/browse/ELY-2547

### CODE REVIEW

**Comment by darranl** [comment]
@lvydra FYI I mentioned this on the Jira issue but I have needed to temporarily revert so have raised a new PR here to restore the change but we are seeing CI failures.

**Comment by lvydra** [comment]
Thanks @darranl, I will look at it.

**Comment by darranl** [comment]
Thanks @lvydra if you have any changes feel free to submit a PR to my topic branch to this or create a new PR yourself and we will close this one - will keep this one here for now so we don't lose your changes.

**Comment by lvydra** [comment]
Hi @darranl I have opened a new PR https://github.com/wildfly-security/wildfly-elytron/pull/2194, and it seems that formerly failing tests are now passing, though there are some other failures, but those don't seem to be related to the changes.

**Comment by darranl** [comment]
Superseded by https://github.com/wildfly-security/wildfly-elytron/pull/2194

**Pull request closed without merging**
