### PR TITLE
[ELY-2665] update org apache.httpcomponents.httpcore from 4.4.15 to 4.4.16

### PR DESCRIPTION
**Pull request by Iscar-daniel**
[ELY-2665] update apache.httpcomponents.httpcore from 4.4.15 to 4.4.16
https://issues.redhat.com/browse/ELY-2665?filter=12364234

### CODE REVIEW

**Comment by skyllarr** [comment]
Thank you for PR @Iscar-daniel ! Please include the issue number at the beginning of the commit message. Thanks!

**Comment by skyllarr** [comment]
@Iscar-daniel Also please specify that the version is from 4.4.15 to 4.4.16 and not just 4.15 , 4.16

**Comment by Iscar-daniel** [comment]
hi @Skyllarr  thanks for the comment. updated ya

**Comment by skyllarr** [comment]
@Iscar-daniel Looks great, just a minor, you can edit the commit message to not include the same line twice, you can remove the superfluous:

```
[ELY-2665] update org.apache.httpcomponents.httpcore from 4.4.15 to 4.4.16
https://issues.redhat.com/browse/ELY-2665?filter=12364234
```

from the commit message by using git commit --amend.

**Comment by Iscar-daniel** [comment]
> @Iscar-daniel Looks great, just a minor, you can edit the commit message to not include the same line twice, you can remove the superfluous:
> 
> ```
> [ELY-2665] update org.apache.httpcomponents.httpcore from 4.4.15 to 4.4.16
> https://issues.redhat.com/browse/ELY-2665?filter=12364234
> ```
> 
> from the commit message by using git commit --amend.

done. I tried to follow on the contributing guide https://github.com/wildfly-security/wildfly-elytron/blob/2.x/CONTRIBUTING.md

**Review by PrarthonaPaul — APPROVED** [review]
Thanks @Iscar-daniel

**Comment by PrarthonaPaul** [comment]
Hi @Iscar-daniel 
It seems that this branch is conflicting with the main branch. Could you please rebase and resolve the conflicts and push again? Thank you!

**Comment by Iscar-daniel** [comment]
> Hi @Iscar-daniel It seems that this branch is conflicting with the main branch. Could you please rebase and resolve the conflicts and push again? Thank you!

fixed

**Comment by PrarthonaPaul** [comment]
Thanks @Iscar-daniel

**Review by fjuma — APPROVED** [review]
Thanks very much @Iscar-daniel!

**Review by skyllarr — APPROVED** [review]

**Pull request merged**
