### PR TITLE
[Ely 2455]: Add a "FAQ for New Contributors" section to the CONTRIBUTING.md file

### PR DESCRIPTION
**Pull request by harshittiwariii**
#2090 
Issue: https://issues.redhat.com/browse/ELY-2455

Follow up:
-Added link to FAQ's section for New contributors.
-Added link to community documentation.

### CODE REVIEW

**Comment by skyllarr** [comment]
@harshittiwariii Thank you for the updates! You can close your old PR if this is the most recent one. But when making updates to your PRs, you can just force push your changes to your branch and then you don't have to open another PR.

This PR currently has 5 commits. Please squash them into a single commit. Thanks!

**Comment by skyllarr** [comment]
@harshittiwariii Let us know if you need help with squashing of commits. You can watch our video for guidance on squashing commits: https://www.youtube.com/watch?v=GM9hAfyV5MI

**Comment by harshittiwariii** [comment]
@Skyllarr Squashed commits and force pushed to branch.
Thank you.

**Comment by harshittiwariii** [comment]
@Skyllarr Can you please review and merge this request.

**Review by darranl — APPROVED** [review]

**Comment by fjuma** [comment]
@harshittiwariii Welcome to the WildFly Elytron project, thanks very much for your contribution, it looks good!

There's just a conflict that needs to be resolved and then we can merge this. Would you be able to rebase to resolve the conflict? If you have any questions on how to do that, feel free to ask. Thanks!

**Comment by harshittiwariii** [comment]
> @harshittiwariii Welcome to the WildFly Elytron project, thanks very much for your contribution, it looks good!
> 
> There's just a conflict that needs to be resolved and then we can merge this. Would you be able to rebase to resolve the conflict? If you have any questions on how to do that, feel free to ask. Thanks!

@fjuma Thank you for the review. Sure, I will fix the issue.

**Comment by harshittiwariii** [comment]
@fjuma @darranl  I think the conflicts has been resolved. I have pushed the changes to this PR

**Comment by skyllarr** [comment]
Hi @harshittiwariii , there is still a conflict in fhe CONTRIBUTING.md file

**Comment by harshittiwariii** [comment]
> Hi @harshittiwariii , there is still a conflict in fhe CONTRIBUTING.md file

@Skyllarr  Can you verify now ?

**Comment by skyllarr** [comment]
Conflict was resolved, thank you @harshittiwariii . Please make sure that this PR contains a single commit, currently there are 7 commits

**Comment by luck3y** [comment]
Replaced by: https://github.com/wildfly-security/wildfly-elytron/pull/2200

**Comment by fjuma** [comment]
Thanks @luck3y! Closing this one.

**Pull request closed without merging**
