### PR TITLE
[ELY-2663] Upgrade org.apache.commons:commons-lang3 from 3.8.1 to 3.13.0

### PR DESCRIPTION
**Pull request by gabrielpadilh4**
Fixes: https://issues.redhat.com/browse/ELY-2663

### CODE REVIEW

**Comment by skyllarr** [comment]
Hi @gabrielpadilh4 , this PR has conflicts that need to be resolved,

**Comment by gabrielpadilh4** [comment]
@Skyllarr conflicts resolved. Thanks.

**Comment by skyllarr** [comment]
@gabrielpadilh4 You can consider submitting a PR for this issue https://issues.redhat.com/browse/WFCORE-6576 . That would involve creating the same upgrade to the wildfly-core rpository https://github.com/wildfly/wildfly-core/blob/main/pom.xml#L172

**Comment by skyllarr** [comment]
@gabrielpadilh4 Thank you!

**Comment by skyllarr** [comment]
@gabrielpadilh4 This PR currently contains 2 commits. Please remove the unneeded commit. Thank you!

**Comment by gabrielpadilh4** [comment]
Hello @Skyllarr i think i was able to solve. Can you review ?

**Review by skyllarr — APPROVED** [review]

**Comment by skyllarr** [comment]
@gabrielpadilh4 Looks great, thank you!

**Review by fjuma — APPROVED** [review]
Thanks @gabrielpadilh4!

**Pull request merged**
