### PR TITLE
[ELY-680] Kerberos logging

### PR DESCRIPTION
**Pull request by honza889**
Based on https://github.com/wildfly-security/wildfly-elytron/pull/516

https://issues.jboss.org/browse/ELY-680

### CODE REVIEW

**Comment by darranl** [comment]
The logging is fine but it was a deliberate decision that we don't expose configuration based on JAAS login modules, before we add those options I would like to know what problems it actually solves.

**Comment by dmlloyd** [comment]
Ah I didn't notice that this was based on #516 - probably this commit should be rebased directly on to master.

**Comment by darranl** [comment]
Yeah if this can be rebased to just add logging without the additional options map it will be good to merge.

**Comment by honza889** [comment]
Removed dependency on rejected change.

**Comment by dmlloyd** [comment]
Seems OK now @darranl ?

**Pull request merged**
