### PR TITLE
[ELY-142] An atomic load KeyStore with test case.

### PR DESCRIPTION
**Pull request by darranl**

### CODE REVIEW

**Comment by darranl** [comment]
Will have another look, the complication is just to get the Provider instance up to the parent KeyStore.

**Comment by dmlloyd** [comment]
See my previous comment.  I think that KeyStore impls need to be thread-safe; the 'initialised' flag should be dropped IMO.

**Comment by darranl** [comment]
There is no longer an initialised flag - are you still seeing it in the diffs?

**Comment by dmlloyd** [comment]
I did... but I think there's some kind of funny caching issue going on with my browser and GitHub lately...

**Pull request merged**
