### PR TITLE
[ELY-1872] elytron-tool.sh usage with symbolic links

### PR DESCRIPTION
**Pull request by ivassile**
https://issues.jboss.org/browse/ELY-1872

### CODE REVIEW

**Comment by darranl** [comment]
@ivassile it looks like this is against the wrong branch - should it be 1.6 instead?

**Comment by ivassile** [comment]
@darranl I thought that we have to first fix it upstream and then I will port it to 1.6 when accepted. I verified and tested the issue with latest WF and Elytron.

**Comment by darranl** [comment]
If this is for a maintenance release please submit against the maintenance branch only.

**Comment by darranl** [comment]
Closing as this needs to go directly to 1.6.x

**Comment by ivassile** [comment]
PR to 1.6.x https://github.com/wildfly-security/wildfly-elytron/pull/1330

**Pull request closed without merging**
