### PR TITLE
[ELY-2368] Add Override annotations to AggregateSecurityRealm

### PR DESCRIPTION
**Pull request by Kshitiz-Mhto**
issue: [ELY-2368](https://issues.redhat.com/browse/ELY-2368)

### CODE REVIEW

**Comment by Kshitiz-Mhto** [comment]
hi! @Skyllarr ,should i fix these warnings also in this PR? 

wilddeprecated

**Comment by skyllarr** [comment]
Hello @Kshitiz-Mhto , no you can leave these and similar warnings as is

**Comment by fjuma** [comment]
Hi @Kshitiz-Mhto, welcome to the WildFly Elytron community! We saw that you've submitted a few PRs already, that's great! Will you be joining us for Open Source Day next week on Sept. 16th?

**Comment by Kshitiz-Mhto** [comment]
hi! @fjuma, i would love to join, network and contribute. is the event virtual ? also is there some criteria for the program, i should know about?

**Comment by fjuma** [comment]
@Kshitiz-Mhto It will be a virtual event for all GHC22 ticket holders. Are you attending GHC22 either virtually or in-person? If so, registration for Open Source Day will open next week on Sept. 13th.

**Comment by Kshitiz-Mhto** [comment]
@fjuma, sry for late reply. To be honest with you, i have some remaining exams on `SEP` `15` ,` 20`,  `25`.  i want to be part of the OSD. i  can manage the schedule for both exam and OSD. i just want your opinion on this? thank you!

**Comment by Kshitiz-Mhto** [comment]
@fjuma i couldnot attend GHC in-person, it is very long way from Nepal to the event so Virtually i guess.  also could you please check your zullip private chat.

**Comment by fjuma** [comment]
Hi @Kshitiz-Mhto, I responded to your question on chat. Feel free to let me know if you have more questions.

**Review by skyllarr — APPROVED** [review]

**Comment by skyllarr** [comment]
@Kshitiz-Mhto Thanks!

**Review by fjuma — APPROVED** [review]
Thanks @Kshitiz-Mhto!

**Pull request merged**
