### PR TITLE
[ELY-2621] Add a test that makes use of the RoleMapper#or method to R…

### PR DESCRIPTION
**Pull request by ericrleung**
…oleMappingTest
https://issues.redhat.com/browse/ELY-2621

### CODE REVIEW

**Comment by PrarthonaPaul** [comment]
Hi @ericrleung welcome to the WildFly Elytron project! Thank you very much for your contribution!
Just a note, for any future PRs you submit, it is a good practice to create a separate branch on your fork and work on it there (I see you are submitting this PR off of 2.x branch from your fork). Generally, we name it after the ELY issue number, but you can name it anything. You can use `git checkout -b <branch name>` to create the branch.

**Review by PrarthonaPaul — APPROVED** [review]
LGTM! Thanks @ericrleung

**Review by PrarthonaPaul — APPROVED** [review]
LGTM!

**Review by fjuma — APPROVED** [review]
Thanks @ericrleung!

**Review by skyllarr — APPROVED** [review]

**Comment by skyllarr** [comment]
@ericrleung Thank you looks great! Just a minor, can you please rebase your change on 2.x branch to resolve the conflict on this PR?

**Comment by skyllarr** [comment]
@ericrleung Thanks!

**Pull request merged**
