### PR TITLE
[ELY-1519] Make restore of SecurityIdentity on replicated session configurable

### PR DESCRIPTION
**Pull request by ivassile**
If the CachedIdentity doesn't have a SecurityIdentity, drop it.

### CODE REVIEW

**Comment by mchoma** [comment]
I dont see configurable aspect of issue. What am I missing?

**Comment by ivassile** [comment]
@mchoma I thought (based on Darran's comment in ELY-1519) that we need this to be the default behaviour and we don't need to be configurable. If we want to configure this option, I can open WFCORE issue and specify the requirements.

**Comment by mchoma** [comment]
At least, this is not what ELY-1519 description is about. 

@darranl did you mean to make it non-configurable? https://issues.jboss.org/browse/ELY-1519?focusedCommentId=13535832&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13535832

I think it can be configurable through SPNEGO mechanism properties. No need for WFCore issue. However if this will end up with new configuration option I think this should be RFE (small/fast) to test /document properly.

**Comment by darranl** [comment]
Maybe some configuration will make sense, this idea now goes to another extreme where all SPNEGO auths will be renegotiated on fail over - this includes cases where delegation is not in use at all.

**Comment by ivassile** [comment]
In clustered environment Security Identity is restored during failover, load balancer change node (not sticky behavior) and session passivation/activation. Added disable-restore-security-identity configuration option which disables this behavior when set to "true".

**Comment by fjuma** [comment]
Going to close this PR since it is against the master branch. There is a corresponding PR against the 1.6.x branch (https://github.com/wildfly-security/wildfly-elytron/pull/1298) so if that one is merged, it will be forward ported to the 1.x and master branches as part of our tagging process.

**Pull request closed without merging**
