### PR TITLE
[ELY-1031] Make the CredentialStore class final

### PR DESCRIPTION
**Pull request by fjuma**
https://issues.jboss.org/browse/ELY-1031

### CODE REVIEW

**Comment by darranl** [comment]
I like this, I just wonder if it risks being an API compatibility issue now we have tagged Final

**Comment by darranl** [comment]
@dmlloyd do you have any thoughts on this one?  I thought we should lock it down to ensure only the SPI is used but the non final version has now gone out in a .Final release so it is potentially an API breaking change.

**Comment by dmlloyd** [comment]
I think making it final is a good idea.  While it is true that a .Final release has gone out, this particular thing is unlikely to have been depended upon already, and will already have been fixed before a Final version of WildFly or a GA version of EAP is in the hands of users.

**Comment by fjuma** [comment]
Closing this one as we will merge via https://github.com/wildfly-security/wildfly-elytron/pull/1009 once it's been ACKed.

**Pull request closed without merging**
