### PR TITLE
[ELY-2668] Upgrade org.jboss.logmanager:jboss-logmanager from 2.1.18.Final to 2.1.19.Final

### PR DESCRIPTION
**Pull request by Iscar-daniel**
[ELY-2668] Upgrade org.jboss.logmanager:jboss-logmanager from 2.1.18.Final to 2.1.19.Final
https://issues.redhat.com/browse/ELY-2668?filter=-1

### CODE REVIEW

**Comment by skyllarr** [comment]
@Iscar-daniel This PR currently contains 2 commits, please remove the unneeded merge commit. Thank you!

**Comment by Iscar-daniel** [comment]
> @Iscar-daniel This PR currently contains 2 commits, please remove the unneeded merge commit. Thank you!

hi @Skyllarr  updated ya thank you

**Review by skyllarr — APPROVED** [review]

**Comment by skyllarr** [comment]
Thank you @Iscar-daniel !

**Comment by skyllarr** [comment]
@Iscar-daniel Just a minor, you can remove the superfluous:

```
[ELY-2668] Upgrade org.jboss.logmanager:jboss-logmanager from 2.1.18.Final to 2.1.19.Final
https://issues.redhat.com/browse/ELY-2668?filter=-1
```

from the commit message

**Comment by Iscar-daniel** [comment]
> @Iscar-daniel Just a minor, you can remove the superfluous:
> 
> ```
> [ELY-2668] Upgrade org.jboss.logmanager:jboss-logmanager from 2.1.18.Final to 2.1.19.Final
> https://issues.redhat.com/browse/ELY-2668?filter=-1
> ```
> 
> from the commit message

fixed. I tried using the guideline here https://github.com/wildfly-security/wildfly-elytron/blob/2.x/CONTRIBUTING.md

**Review by PrarthonaPaul — APPROVED** [review]
Thanks @Iscar-daniel

**Comment by PrarthonaPaul** [comment]
Hi @Iscar-daniel 
It seems that this branch is conflicting with the main branch.
Would you be able to rebase and resolve the conflicts? If you have any questions about how to do this, please feel free to let me know :)
Thanks!

**Comment by Iscar-daniel** [comment]
> Hi @Iscar-daniel It seems that this branch is conflicting with the main branch. Would you be able to rebase and resolve the conflicts? If you have any questions about how to do this, please feel free to let me know :) Thanks!

hi, fixed ya

**Comment by PrarthonaPaul** [comment]
Thanks @Iscar-daniel

**Review by fjuma — APPROVED** [review]
Thanks @Iscar-daniel!

**Pull request merged**
