### PR TITLE
[ELY-2849] upgrade the commons-io.commons-io dependency from 2.7 to 2…

### PR DESCRIPTION
**Pull request by laurastreet**
….16.1

https://issues.redhat.com/browse/ELY-2849

### CODE REVIEW

**Comment by SoniaZaldana** [comment]
Thanks @laurastreet! Could you please link the Jira issue in the description?

**Comment by luck3y** [comment]
Thanks @laurastreet! One thing to remember is to add a link to the Jira issue in the commit box above.

**Review by fjuma — APPROVED** [review]
Look great @laurastreet!

Just a very small comment, it's good practice to include the link to the issue in the issue description (just makes it easy for reviewers to quickly pull up the issue description and see what it was about).

**Review by luck3y — APPROVED** [review]

**Review by ivassile — APPROVED** [review]

**Comment by PrarthonaPaul** [comment]
It seems like there is a CI error that is not related to this PR. @fjuma would you be able to restart the CI jobs?

**Comment by fjuma** [comment]
Restarted the jobs.

**Pull request merged**
