### PR TITLE
[ELY-2395] Add missing ranges for wildfly-elytron-auth-server to ELY_Messages.txt

### PR DESCRIPTION
**Pull request by Tanya-11**
https://issues.redhat.com/browse/ELY-2395

### CODE REVIEW

**Review by fjuma — COMMENTED** [review]
Thanks @Tanya-11! Just one very small comment, it's good to keep the modules in alphabetical order just so it's easy to look things up when needed. Since `wildfly-elytron-auth-server` comes before `wildfly-elytron-auth-util` alphabetically, it would be good to move these four lines above the `wildfly-elytron-auth-util` lines.

**Comment by Tanya-11** [comment]
Hi @fjuma 
I didn't consider the alphabetical order, based on the last word in `wildfly-elytron-auth-server` . Thanks you pointing that out. I've made the changes. Pls review them.
Also, Do I need to squash the commits?

**Comment by fjuma** [comment]
Thanks for the update, @Tanya-11! Yes, please squash the commits. Thanks!

**Comment by fjuma** [comment]
@Tanya-11 It looks like some other commits have been included in this PR. When you get a chance, please rebase this. Feel free to let us know if you need any help with that. Thanks!

**Comment by Tanya-11** [comment]
@fjuma, pls review this PR. Thanks

**Comment by fjuma** [comment]
Hi @Tanya-11, the last commit in this PR looks good. Once this has been rebased / the other commits have been removed, this one will be good to merge. Thanks!

**Comment by Tanya-11** [comment]
> Hi @Tanya-11, the last commit in this PR looks good. Once this has been rebased / the other commits have been removed, this one will be good to merge. Thanks!

Hi @fjuma, I've removed the previous commits. Thanks!

**Review by fjuma — APPROVED** [review]
Perfect thanks!

**Review by skyllarr — APPROVED** [review]

**Comment by skyllarr** [comment]
@Tanya-11 Thank you

**Pull request merged**
