### PR TITLE
DISCUSSION - Real callbacks in tests

### PR DESCRIPTION
**Pull request by kabir**
This contains https://github.com/wildfly-security/wildfly-elytron/pull/251 but also attempts to make the DIGEST tests use the real callbacks. To get this working, I needed to make a few fixes to the core codebase, and I will try to summarise the rationale for the changes for each commit here. I also have a few general observations.

## Rationale for commits
If you are really curious, you can delete each of these commits and watch various tests in DigestTest blow up. The summary for each commit follows.

###### Better realm negotiation?
https://github.com/wildfly-security/wildfly-elytron/pull/242 was merged and made it possible to configure which realm a client uses and to recognise the realm callback on the client. However, if this method is not called, as was the case in the default realm tests (look for usage of e.g. 

    createClearPwdClientCallbackHandler("George", "gpwd", null);

 in DigestTest, the key being the null realm parameter), the realm callback does not get handled on the client. 

###### Implement RealmChoiceCallback handling on the client
I ported the logic to deal with choosing realms on the client from ServerCallbackHandler

###### Use real callback handlers for digest test
This was my aim, the previous commits allow this to happen

###### Delete client callback handler
R.I.P. :-)

###### tmp Attempt authzid
Will be discussed further below

###### Realm mismatch?!?
I am not clear if the realm being negotiated by the Sasl Digest mechanism has anything to do with the realm used in the security domain or if they are different concepts which just happen to be named realm. See e.g. my comment in DigestTest.testSuccessfulExchange(). The issue is that the SaslServerBuilder by default creates a realm called `mainRealm` to which the test user is added. However, then the tests negotiate either `TestRealm` or `TestServer`. I had really expected to need to call SaslServerBuilder.setRealmName() to the value of the negotiated realm name (i.e. `TestServer` or `TestRealm`) so that the security domain builder would have added the user to that realm rather than to `mainRealm`?

###### Still using custom callback handlers
There are still some tests which are using custom callback handlers
* Entity
  * The ServerAuthenticationContext’s CBH misses handling of TrustedAuthoritiesCallback
* Gs2
  * At the time I compiled this list, I didn’t do this since I hadn’t figured out how to set the channel binding stuff. I have since worked out how to do that, so this might be easy to port
* GSSApi
  * I have not looked yet, it is pretty complex
* OTP
  * The ServerAuthenticationContext’s CBH misses handling of TrustedAuthoritiesCallback, CredentialUpdateCallback and TimeoutUpdateCallback

###### ServerCallbackHandler/authzid
I haven’t been able to nuke ServerCallbackHandler yet. It is still being used by testAuthorizationId() and testStrangeCredentials() in ScramClientCompatibilityTest. I have tried to change these but with the domain set up as in the commit *tmp Attempt authzid*, I get an error:
```
javax.security.sasl.SaslException: ELY05014: [SCRAM-SHA-1] SASL authorization failed: "admin" is not authorized to act on behalf of "user"
	at org.wildfly.security._private.ElytronMessages_$logger.saslAuthorizationFailed(ElytronMessages_$logger.java:1667)
	at org.wildfly.security.sasl.scram.ScramSaslServer.evaluateMessage(ScramSaslServer.java:389)
	at org.wildfly.security.sasl.util.AbstractSaslParticipant.evaluateMessage(AbstractSaslParticipant.java:177)
	at org.wildfly.security.sasl.util.AbstractSaslServer.evaluateResponse(AbstractSaslServer.java:52)
	at org.wildfly.security.sasl.util.AuthenticationCompleteCallbackSaslServerFactory$1.evaluateResponse(AuthenticationCompleteCallbackSaslServerFactory.java:58)
	at org.wildfly.security.sasl.scram.ScramServerCompatibilityTest.testAllowedAuthorizationId(ScramServerCompatibilityTest.java:207)
```
Originally I had it as 
```
        final SaslServer saslServer =
                new SaslServerBuilder(ScramSaslServerFactory.class, Scram.SCRAM_SHA_1)
                        .setUserName("user")
                        .setPassword(ClearPassword.ALGORITHM_CLEAR, new ClearPasswordSpec("pencil".toCharArray()))
                        .build();
```
But then I get
```
javax.security.sasl.SaslException: ELY05051: [SCRAM-SHA-1] Callback handler does not support credential acquisition
	at org.wildfly.security._private.ElytronMessages_$logger.saslCallbackHandlerDoesNotSupportCredentialAcquisition(ElytronMessages_$logger.java:2074)
	at org.wildfly.security.sasl.scram.ScramSaslServer.evaluateMessage(ScramSaslServer.java:211)
	at org.wildfly.security.sasl.util.AbstractSaslParticipant.evaluateMessage(AbstractSaslParticipant.java:177)
	at org.wildfly.security.sasl.util.AbstractSaslServer.evaluateResponse(AbstractSaslServer.java:52)
	at org.wildfly.security.sasl.util.AuthenticationCompleteCallbackSaslServerFactory$1.evaluateResponse(AuthenticationCompleteCallbackSaslServerFactory.java:58)
	at org.wildfly.security.sasl.scram.ScramServerCompatibilityTest.testAllowedAuthorizationId(ScramServerCompatibilityTest.java:202)
```
The problem there is that there is no entry in the security domain for the ‘admin’ user (only for ‘user’) so CredentialSupport.UNSUPPORTED is returned at:
```
getCredentialSupport():143, SimpleMapBackedSecurityRealm$SimpleMapRealmIdentity {org.wildfly.security.auth.provider}
getCredentialSupport():826, ServerAuthenticationContext$NameAssignedState {org.wildfly.security.auth.server}
getCredentialSupport():448, ServerAuthenticationContext {org.wildfly.security.auth.server}
handleOne():600, ServerAuthenticationContext$2 {org.wildfly.security.auth.server}
handleOne():549, ServerAuthenticationContext$2 {org.wildfly.security.auth.server}
handle():528, ServerAuthenticationContext$2 {org.wildfly.security.auth.server}
tryHandleCallbacks():98, AbstractSaslParticipant {org.wildfly.security.sasl.util}
getSaltedPasswordFromTwoWay():497, ScramSaslServer {org.wildfly.security.sasl.scram}
evaluateMessage():205, ScramSaslServer {org.wildfly.security.sasl.scram}
evaluateMessage():177, AbstractSaslParticipant {org.wildfly.security.sasl.util}
evaluateResponse():52, AbstractSaslServer {org.wildfly.security.sasl.util}
evaluateResponse():58, AuthenticationCompleteCallbackSaslServerFactory$1 {org.wildfly.security.sasl.util}
testAllowedAuthorizationId():202, ScramServerCompatibilityTest {org.wildfly.security.sasl.scram}
```

### CODE REVIEW

**Comment by dmlloyd** [comment]
For "Better realm negotiation?", I wonder if we should maybe always support realm callback by adding a call to .useRealm() with a null realm to org.wildfly.security.auth.client.AuthenticationConfiguration#EMPTY (see line 157 of that class).  This way, there's always going to be *something* to handle that realm callback, even if it's just a null value.

**Comment by honza889** [comment]
>I am not clear if the realm being negotiated by the Sasl Digest mechanism has anything to do with the realm used in the security domain or if they are different concepts which just happen to be named realm.

Different concepts.

**Comment by honza889** [comment]
> The problem there is that there is no entry in the security domain for the ‘admin’ user (only for ‘user’) so CredentialSupport.UNSUPPORTED is returned

Hm, DigestSaslServer not support TwoWayPassword credential yet. Only old PasswordCallback and already salted DigestPassword credential is supported. I will add it. For now you can use DigestPassword.

**Comment by kabir** [comment]
Superseded by https://github.com/wildfly-security/wildfly-elytron/pull/265

**Pull request closed without merging**
