### PR TITLE
[ELY-1603] Add missing HTTP mechanisms to the WildFlyElytronProvider initialisation.

### PR DESCRIPTION
**Pull request by darranl**
https://issues.jboss.org/browse/ELY-1603

### CODE REVIEW

**Comment by mchoma** [comment]
With this change are we exposing two new authentication mechanism in web.xml? If yes, this is RFE territory in my opinion. QA nack - RFE

**Comment by darranl** [comment]
This is only cleaning up the provider, the mechanisms are already exposed.

**Comment by darranl** [comment]
These mechanisms have been usable since commit 9fbcaf523133edfea65a102fa760607848961727 so the first tag to contain this commit was 1.2.0.Beta12

**Comment by mchoma** [comment]
QA ack - not RFE

**Pull request merged**
