### PR TITLE
[ELY-2465] JsonSerialization#createObjectNode should throw its exception using ElytronMessages

### PR DESCRIPTION
**Pull request by lvydra**
https://issues.redhat.com/browse/ELY-2465

### CODE REVIEW

**Review by jessicarod7 — CHANGES_REQUESTED** [review]
Hey, looks good! Although it's a bit inconsistent, generally we prefer to keep the `ElytronMessages` class in a `_private` folder ([example](https://github.com/wildfly-security/wildfly-elytron/blob/1.x/x500/base/src/main/java/org/wildfly/security/x500/_private/ElytronMessages.java)). Could you move the class into a matching folder and update the interface to be public?

**Comment by lvydra** [comment]
Hi @cam-rod, thanks for the review, PR should be updated now.

**Review by fjuma — APPROVED** [review]
Thanks @lvydra!

**Comment by jessicarod7** [comment]
Looks good, thanks @lvydra!

**Review by skyllarr — APPROVED** [review]

**Pull request merged**
