### PR TITLE
[ELY-2662] Upgrade jakarta.json:jakarta.json-api from 2.0.0 to 2.1.2

### PR DESCRIPTION
**Pull request by gabrielpadilh4**
Fixes: https://issues.redhat.com/browse/ELY-2662

### CODE REVIEW

**Review by skyllarr — APPROVED** [review]
Thanks @gabrielpadilh4 !

**Comment by fjuma** [comment]
@gabrielpadilh4 Thanks for the PR! Looks like there are related test failures in CI:

https://github.com/wildfly-security/wildfly-elytron/actions/runs/6633479695/job/18021291993?pr=2046

**Comment by gabrielpadilh4** [comment]
Hello @fjuma @Skyllarr it seems that jakarta.json 2.1 removed the default implementation from the specification api[1].

The implementation is eclipse parsson which changed some artifacts from `org.glassfish` to `org.eclipse.parsson` on version 1.0, see [2]

Based on that, i also changed the `org.glassfish` dependencies to `org.eclipse.parsson` and version 1.1.3 that it is the latest.

What do you think ?


[1] https://jakarta.ee/specifications/jsonp/2.1/
[2] https://projects.eclipse.org/projects/ee4j.parsson/releases/1.0.0/plan

**Comment by fjuma** [comment]
> Hello @fjuma @Skyllarr it seems that jakarta.json 2.1 removed the default implementation from the specification api[1].
> 
> The implementation is eclipse parsson which changed some artifacts from `org.glassfish` to `org.eclipse.parsson` on version 1.0, see [2]
> 
> Based on that, i also changed the `org.glassfish` dependencies to `org.eclipse.parsson` and version 1.1.3 that it is the latest.
> 
> What do you think ?
> 
> [1] https://jakarta.ee/specifications/jsonp/2.1/ [2] https://projects.eclipse.org/projects/ee4j.parsson/releases/1.0.0/plan

Thanks for the update, @gabrielpadilh4!

@PrarthonaPaul Would you be able to check if this aligns with what is currently used by WildFly?

**Comment by PrarthonaPaul** [comment]
> > Hello @fjuma @Skyllarr it seems that jakarta.json 2.1 removed the default implementation from the specification api[1].
> > The implementation is eclipse parsson which changed some artifacts from `org.glassfish` to `org.eclipse.parsson` on version 1.0, see [2]
> > Based on that, i also changed the `org.glassfish` dependencies to `org.eclipse.parsson` and version 1.1.3 that it is the latest.
> > What do you think ?
> > [1] https://jakarta.ee/specifications/jsonp/2.1/ [2] https://projects.eclipse.org/projects/ee4j.parsson/releases/1.0.0/plan
> 
> Thanks for the update, @gabrielpadilh4!
> 
> @PrarthonaPaul Would you be able to check if this aligns with what is currently used by WildFly?

It looks like WildFly-core still uses Glassfish: https://github.com/wildfly/wildfly-core/blob/43143580a4b60fef3671c557588d587c492ade1b/pom.xml#L205
same with wildfly it seems: 
https://github.com/wildfly/wildfly/blob/a3a43c0bae70d14fee13e34cbdb5898f5cd47139/boms/user/client/jms-client/pom.xml#L104-L107
But the wildfly parent pom doesn't have either

**Comment by gabrielpadilh4** [comment]
@PrarthonaPaul also it's good to mention that wildfly-core uses version 1.1.6 of jakarta json glassfish while elytron uses 2.0.0

[        <version.org.glassfish.jakarta.json>1.1.6</version.org.glassfish.jakarta.json>](https://github.com/wildfly/wildfly-core/blob/43143580a4b60fef3671c557588d587c492ade1b/pom.xml#L205C4-L205C4)

[        <version.org.glassfish.jakarta.json>2.0.0</version.org.glassfish.jakarta.json>](https://github.com/wildfly-security/wildfly-elytron/blob/21c83155cdce90a53cb0aa70aba409a86e77bfb6/pom.xml#L85C3-L85C3)

**Comment by darranl** [comment]
Thank you for the PR, FYI I have just resubmitted here to resolve the merge conflict https://github.com/wildfly-security/wildfly-elytron/pull/2111

**Pull request closed without merging**
