### PR TITLE
[ELY-2557] Add an afterclass method to do clean-up after the FileSystemEncryptRealmCommandTest testBulkWithoutNames test

### PR DESCRIPTION
**Pull request by lvydra**
https://issues.redhat.com/browse/ELY-2557
follow up to: https://github.com/wildfly-security/wildfly-elytron/pull/1892

### CODE REVIEW

**Comment by ivassile** [comment]
@Skyllarr LGTM

**Review by ivassile — APPROVED** [review]
The changes looks good to me

**Comment by skyllarr** [comment]
@lvydra I can't re-run the CI for this PR, possibly because the last run is now outdated.. Can you please rebase this to see what the failures in the CI were for?

**Comment by lvydra** [comment]
@Skyllarr rebased

**Review by skyllarr — APPROVED** [review]

**Comment by skyllarr** [comment]
Thanks @lvydra !

**Pull request merged**
