### PR TITLE
[ELY-2728] Upgrade japicmp-maven-plugin to 0.20.0 so we can build with JDK 21

### PR DESCRIPTION
**Pull request by ivassile**
Issue: https://issues.redhat.com/browse/ELY-2768
Upstream issue: https://issues.redhat.com/browse/ELY-2728
Upstream PR: https://github.com/wildfly-security/wildfly-elytron/pull/2106

### CODE REVIEW

**Review by fjuma — APPROVED** [review]

**Comment by fjuma** [comment]
@ivassile Just noticed, shouldn't this be against 2.2.x?

**Comment by fjuma** [comment]
@ivassile I also just noticed that this is a duplicate of https://issues.redhat.com/browse/ELY-2765 (sorry about that!) so maybe we can just close this PR and mark the issue as a duplicate.

**Comment by ivassile** [comment]
> https://issues.redhat.com/browse/ELY-2765

Sorry for creating this issue. Didn't see it. I'll close it. Thanks!

**Comment by ivassile** [comment]
Duplicate of https://github.com/wildfly-security/wildfly-elytron/pull/2148

**Pull request closed without merging**
