### PR TITLE
[ELY-1398] Add support for public API compatibility check using SigTest

### PR DESCRIPTION
**Pull request by mchoma**
Using SigTest tool [1] two profiles were created
1. to generate method signature file *.sigfile into local maven
repository
2. and check against specified version releasedVersion

Usage:
mvn install -PmethodSignatureGenerate -DskipTests
mvn install -PmethodSignatureCheck -DskipTests

This expects during Elytron release process *.sigfile from local maven
repository will be deployed into central maven repository.

[1] http://wiki.netbeans.org/SigTest

### CODE REVIEW

**Comment by mchoma** [comment]
This is follow up on https://github.com/wildfly-security/wildfly-elytron/pull/1038

**Comment by dmlloyd** [comment]
I don't like that we'd have to maintain the sigfile artifacts.  Couldn't we just generate the sigfile for the old and new versions directly from the JAR artifacts?

**Comment by mchoma** [comment]
It is not possible with SigTest tool. But should be possible with japicmp

[1]  https://github.com/siom79/japicmp

**Comment by mchoma** [comment]
Closing SigTest approach in favour of japicmp approach. Japicmp is able to compare two jars - no need to maintain proprietary sigfile. https://github.com/wildfly-security/wildfly-elytron/pull/1067

**Pull request closed without merging**
