### PR TITLE
[ELY-1494] disabled PKCS12 KeyStore test for HP, removed unnecessary workaround

### PR DESCRIPTION
**Pull request by hkalina**
https://issues.jboss.org/browse/ELY-1494

* disabled testing of PKCS12 for all non-Oracle JDKS (OpenJDK is Oracle)
* removed workaround for older Oracle JDK 8 (not needed already) and IBM (not sufficient for PKCS12) - see issue comment

### CODE REVIEW

**Comment by darranl** [comment]
Do we have a follow up Jira so we can look at this again in the future?

**Comment by hkalina** [comment]
PKCS12+PasswordCredential will not work on IBM at all, as it pass everything into spec, custom made object will fail.
Not sure about HP - but two possibilities:
* a) there will be the same problem as on IBM and custom object cannot be stored into PKCS12 here
* b) it will require to test against signed elytron JAR - not possible as junit/surefire tests of elytron itself
I would recommend to not re-enable testing of PKCS12 in this test in future - if we want to test it, external tests using signed JAR of elytron would be better.

**Comment by darranl** [comment]
Maybe make sure we have a follow up Jira with your ideas for HP and we can decide if we want to pick them up later.  We may need to make sure for both of these we have some docs to highlight the differences on IBM and HP.

**Comment by hkalina** [comment]
@darranl created following up issue https://issues.jboss.org/browse/ELY-1496

**Pull request merged**
