### PR TITLE
[ELY-2467] Update test cases in CipherSuiteSelectorTest to use a common helper method where appropriate

### PR DESCRIPTION
**Pull request by dheerajodha**
https://issues.redhat.com/browse/ELY-2467

### CODE REVIEW

**Review by skyllarr — APPROVED** [review]

**Review by fjuma — APPROVED** [review]
Thanks @dheerajodha!

**Comment by dheerajodha** [comment]
Thank you @fjuma :-)

I have one question, sorry for asking after the PR got merged... I noticed that a test failed here in the CI, and I tried to find out why it was failing but I couldn't understand the reason because before creating a PR I made sure that all my tests passed with `mvn test`. And recently when I tried to rerun this command locally, I noticed a test failure on a different class. So, this was a little confusing, is it safe to assume that it's normal and had nothing to do with my changes as part of this PR?

**Comment by fjuma** [comment]
Hi @dheerajodha, CI passed on the PR (if you click on the details above, it shows 3 checks passed). 
Which tests are failing for you locally?

**Comment by dheerajodha** [comment]
@fjuma,
- Yes, when I click on the "Checks" tab above I see 3 checks passed.
- But I remember seeing a failure when I created this PR...here's what I see in the first run triggered by me (you can [check it out on its link here](https://github.com/wildfly-security/wildfly-elytron/actions/runs/3299491645/jobs/5442914892))

image

- But it passed when Diana triggered it once again. So, I just got curious...

- When I run ` mvn test -rf :wildfly-elytron-tool` locally, I've attached a screenshot of my output below. Although it might be due to some error from my end when I was trying to git squash...
image

Can you please correct me?

**Comment by fjuma** [comment]
@dheerajodha Ah, I see. Looks like the original CI failure was an intermittent failure in an unrelated test.

You could try rebasing and doing a clean build to see if that helps resolve the failures. If not, feel free to copy/paste the stack trace / more details about the failures and we can take a look to see if there's something in your environment that's causing them.

**Comment by dheerajodha** [comment]
Sure thanks!
I did a clean build by using `mvn clean install` and then I ran `mvn test` which gave me errors as shown below:

<details>
<summary> Error </summary>

`-------------------------------------------------------------------------------
Test set: org.wildfly.security.tool.FileSystemEncryptRealmCommandTest
-------------------------------------------------------------------------------
Tests run: 8, Failures: 0, Errors: 5, Skipped: 0, Time elapsed: 0.424 sec <<< FAILURE! - in org.wildfly.security.tool.FileSystemEncryptRealmCommandTest
testBulk(org.wildfly.security.tool.FileSystemEncryptRealmCommandTest)  Time elapsed: 0.288 sec  <<< ERROR!
java.lang.RuntimeException: org.wildfly.security.auth.server.RealmUnavailableException: ELY01024: Filesystem-backed realm cannot create duplicate identity for identity "anotherUser"
	at org.wildfly.security.tool.AbstractCommandTest.executeCommandAndCheckStatus(AbstractCommandTest.java:89)
	at org.wildfly.security.tool.AbstractCommandTest.executeCommandAndCheckStatus(AbstractCommandTest.java:80)
	at org.wildfly.security.tool.FileSystemEncryptRealmCommandTest.runCommand(FileSystemEncryptRealmCommandTest.java:73)
	at org.wildfly.security.tool.FileSystemEncryptRealmCommandTest.testBulk(FileSystemEncryptRealmCommandTest.java:108)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: org.wildfly.security.auth.server.RealmUnavailableException: ELY01024: Filesystem-backed realm cannot create duplicate identity for identity "anotherUser"
	at org.wildfly.security.auth.realm.FileSystemSecurityRealm$Identity.createPrivileged(FileSystemSecurityRealm.java:874)
	at org.wildfly.security.auth.realm.FileSystemSecurityRealm$Identity.create(FileSystemSecurityRealm.java:808)
	at org.wildfly.security.auth.realm.FileSystemRealmUtil.createEncryptedRealmFromUnencrypted(FileSystemRealmUtil.java:56)
	at org.wildfly.security.tool.FileSystemEncryptRealmCommand.createFileSystemRealm(FileSystemEncryptRealmCommand.java:722)
	at org.wildfly.security.tool.FileSystemEncryptRealmCommand.execute(FileSystemEncryptRealmCommand.java:408)
	at org.wildfly.security.tool.AbstractCommandTest.executeCommandAndCheckStatus(AbstractCommandTest.java:87)
	... 33 more
Caused by: java.nio.file.FileAlreadyExistsException: target/test-classes/filesystem-encrypt/fs-encrypted-realms/multiple-credential-types/M/MFXG65DIMVZFK43FOI.xml -> target/test-classes/filesystem-encrypt/fs-encrypted-realms/multiple-credential-types/M/MFXG65DIMVZFK43FOI.xml.YMO0K4MT7J04
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:94)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.createLink(UnixFileSystemProvider.java:481)
	at java.base/java.nio.file.Files.createLink(Files.java:1102)
	at org.wildfly.security.auth.realm.FileSystemSecurityRealm$Identity.createPrivileged(FileSystemSecurityRealm.java:867)
	... 38 more

testSingleUserAndVerify(org.wildfly.security.tool.FileSystemEncryptRealmCommandTest)  Time elapsed: 0.011 sec  <<< ERROR!
java.lang.RuntimeException: org.wildfly.security.auth.server.RealmUnavailableException: ELY01024: Filesystem-backed realm cannot create duplicate identity for identity "hello"
	at org.wildfly.security.tool.AbstractCommandTest.executeCommandAndCheckStatus(AbstractCommandTest.java:89)
	at org.wildfly.security.tool.AbstractCommandTest.executeCommandAndCheckStatus(AbstractCommandTest.java:80)
	at org.wildfly.security.tool.FileSystemEncryptRealmCommandTest.runCommand(FileSystemEncryptRealmCommandTest.java:67)
	at org.wildfly.security.tool.FileSystemEncryptRealmCommandTest.testSingleUserAndVerify(FileSystemEncryptRealmCommandTest.java:178)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: org.wildfly.security.auth.server.RealmUnavailableException: ELY01024: Filesystem-backed realm cannot create duplicate identity for identity "hello"
	at org.wildfly.security.auth.realm.FileSystemSecurityRealm$Identity.createPrivileged(FileSystemSecurityRealm.java:874)
	at org.wildfly.security.auth.realm.FileSystemSecurityRealm$Identity.create(FileSystemSecurityRealm.java:808)
	at org.wildfly.security.auth.realm.FileSystemRealmUtil.createEncryptedRealmFromUnencrypted(FileSystemRealmUtil.java:56)
	at org.wildfly.security.tool.FileSystemEncryptRealmCommand.createFileSystemRealm(FileSystemEncryptRealmCommand.java:722)
	at org.wildfly.security.tool.FileSystemEncryptRealmCommand.execute(FileSystemEncryptRealmCommand.java:408)
	at org.wildfly.security.tool.AbstractCommandTest.executeCommandAndCheckStatus(AbstractCommandTest.java:87)
	... 33 more
Caused by: java.nio.file.FileAlreadyExistsException: ./target/test-classes/filesystem-encrypt/fs-encrypted-realms/verify/N/B/NBSWY3DP.xml -> ./target/test-classes/filesystem-encrypt/fs-encrypted-realms/verify/N/B/NBSWY3DP.xml.GSU5BU0NFBIR
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:94)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.createLink(UnixFileSystemProvider.java:481)
	at java.base/java.nio.file.Files.createLink(Files.java:1102)
	at org.wildfly.security.auth.realm.FileSystemSecurityRealm$Identity.createPrivileged(FileSystemSecurityRealm.java:867)
	... 38 more

testSingleUserWithRolesAndKey(org.wildfly.security.tool.FileSystemEncryptRealmCommandTest)  Time elapsed: 0.013 sec  <<< ERROR!
java.lang.RuntimeException: org.wildfly.security.auth.server.RealmUnavailableException: ELY01024: Filesystem-backed realm cannot create duplicate identity for identity "secretperson"
	at org.wildfly.security.tool.AbstractCommandTest.executeCommandAndCheckStatus(AbstractCommandTest.java:89)
	at org.wildfly.security.tool.AbstractCommandTest.executeCommandAndCheckStatus(AbstractCommandTest.java:80)
	at org.wildfly.security.tool.FileSystemEncryptRealmCommandTest.runCommand(FileSystemEncryptRealmCommandTest.java:67)
	at org.wildfly.security.tool.FileSystemEncryptRealmCommandTest.testSingleUserWithRolesAndKey(FileSystemEncryptRealmCommandTest.java:164)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: org.wildfly.security.auth.server.RealmUnavailableException: ELY01024: Filesystem-backed realm cannot create duplicate identity for identity "secretperson"
	at org.wildfly.security.auth.realm.FileSystemSecurityRealm$Identity.createPrivileged(FileSystemSecurityRealm.java:874)
	at org.wildfly.security.auth.realm.FileSystemSecurityRealm$Identity.create(FileSystemSecurityRealm.java:808)
	at org.wildfly.security.auth.realm.FileSystemRealmUtil.createEncryptedRealmFromUnencrypted(FileSystemRealmUtil.java:56)
	at org.wildfly.security.tool.FileSystemEncryptRealmCommand.createFileSystemRealm(FileSystemEncryptRealmCommand.java:722)
	at org.wildfly.security.tool.FileSystemEncryptRealmCommand.execute(FileSystemEncryptRealmCommand.java:408)
	at org.wildfly.security.tool.AbstractCommandTest.executeCommandAndCheckStatus(AbstractCommandTest.java:87)
	... 33 more
Caused by: java.nio.file.FileAlreadyExistsException: ./target/test-classes/filesystem-encrypt/fs-encrypted-realms/single-user-with-key/O/N/ONSWG4TFORYGK4TTN5XA.xml -> ./target/test-classes/filesystem-encrypt/fs-encrypted-realms/single-user-with-key/O/N/ONSWG4TFORYGK4TTN5XA.xml.V1CEZBMQQV3V
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:94)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.createLink(UnixFileSystemProvider.java:481)
	at java.base/java.nio.file.Files.createLink(Files.java:1102)
	at org.wildfly.security.auth.realm.FileSystemSecurityRealm$Identity.createPrivileged(FileSystemSecurityRealm.java:867)
	... 38 more

testSingleUserWithRoles(org.wildfly.security.tool.FileSystemEncryptRealmCommandTest)  Time elapsed: 0.012 sec  <<< ERROR!
java.lang.RuntimeException: org.wildfly.security.auth.server.RealmUnavailableException: ELY01024: Filesystem-backed realm cannot create duplicate identity for identity "person123"
	at org.wildfly.security.tool.AbstractCommandTest.executeCommandAndCheckStatus(AbstractCommandTest.java:89)
	at org.wildfly.security.tool.AbstractCommandTest.executeCommandAndCheckStatus(AbstractCommandTest.java:80)
	at org.wildfly.security.tool.FileSystemEncryptRealmCommandTest.runCommand(FileSystemEncryptRealmCommandTest.java:61)
	at org.wildfly.security.tool.FileSystemEncryptRealmCommandTest.testSingleUserWithRoles(FileSystemEncryptRealmCommandTest.java:150)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: org.wildfly.security.auth.server.RealmUnavailableException: ELY01024: Filesystem-backed realm cannot create duplicate identity for identity "person123"
	at org.wildfly.security.auth.realm.FileSystemSecurityRealm$Identity.createPrivileged(FileSystemSecurityRealm.java:874)
	at org.wildfly.security.auth.realm.FileSystemSecurityRealm$Identity.create(FileSystemSecurityRealm.java:808)
	at org.wildfly.security.auth.realm.FileSystemRealmUtil.createEncryptedRealmFromUnencrypted(FileSystemRealmUtil.java:56)
	at org.wildfly.security.tool.FileSystemEncryptRealmCommand.createFileSystemRealm(FileSystemEncryptRealmCommand.java:722)
	at org.wildfly.security.tool.FileSystemEncryptRealmCommand.execute(FileSystemEncryptRealmCommand.java:408)
	at org.wildfly.security.tool.AbstractCommandTest.executeCommandAndCheckStatus(AbstractCommandTest.java:87)
	... 33 more
Caused by: java.nio.file.FileAlreadyExistsException: ./target/test-classes/filesystem-encrypt/fs-encrypted-realms/single-user-with-role/O/B/S/OBSXE43PNYYTEMY.xml -> ./target/test-classes/filesystem-encrypt/fs-encrypted-realms/single-user-with-role/O/B/S/OBSXE43PNYYTEMY.xml.QV0X6UP93L2O
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:94)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.createLink(UnixFileSystemProvider.java:481)
	at java.base/java.nio.file.Files.createLink(Files.java:1102)
	at org.wildfly.security.auth.realm.FileSystemSecurityRealm$Identity.createPrivileged(FileSystemSecurityRealm.java:867)
	... 38 more

testSingleUser(org.wildfly.security.tool.FileSystemEncryptRealmCommandTest)  Time elapsed: 0.01 sec  <<< ERROR!
java.lang.RuntimeException: org.wildfly.security.auth.server.RealmUnavailableException: ELY01024: Filesystem-backed realm cannot create duplicate identity for identity "hello"
	at org.wildfly.security.tool.AbstractCommandTest.executeCommandAndCheckStatus(AbstractCommandTest.java:89)
	at org.wildfly.security.tool.AbstractCommandTest.executeCommandAndCheckStatus(AbstractCommandTest.java:80)
	at org.wildfly.security.tool.FileSystemEncryptRealmCommandTest.runCommand(FileSystemEncryptRealmCommandTest.java:55)
	at org.wildfly.security.tool.FileSystemEncryptRealmCommandTest.testSingleUser(FileSystemEncryptRealmCommandTest.java:128)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: org.wildfly.security.auth.server.RealmUnavailableException: ELY01024: Filesystem-backed realm cannot create duplicate identity for identity "hello"
	at org.wildfly.security.auth.realm.FileSystemSecurityRealm$Identity.createPrivileged(FileSystemSecurityRealm.java:874)
	at org.wildfly.security.auth.realm.FileSystemSecurityRealm$Identity.create(FileSystemSecurityRealm.java:808)
	at org.wildfly.security.auth.realm.FileSystemRealmUtil.createEncryptedRealmFromUnencrypted(FileSystemRealmUtil.java:56)
	at org.wildfly.security.tool.FileSystemEncryptRealmCommand.createFileSystemRealm(FileSystemEncryptRealmCommand.java:722)
	at org.wildfly.security.tool.FileSystemEncryptRealmCommand.execute(FileSystemEncryptRealmCommand.java:408)
	at org.wildfly.security.tool.AbstractCommandTest.executeCommandAndCheckStatus(AbstractCommandTest.java:87)
	... 33 more
Caused by: java.nio.file.FileAlreadyExistsException: ./target/test-classes/filesystem-encrypt/fs-encrypted-realms/single-user/N/B/NBSWY3DP.xml -> ./target/test-classes/filesystem-encrypt/fs-encrypted-realms/single-user/N/B/NBSWY3DP.xml.ABMLV9PWHOYG
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:94)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.createLink(UnixFileSystemProvider.java:481)
	at java.base/java.nio.file.Files.createLink(Files.java:1102)
	at org.wildfly.security.auth.realm.FileSystemSecurityRealm$Identity.createPrivileged(FileSystemSecurityRealm.java:867)
	... 38 more
`
</details>

**Comment by fjuma** [comment]
@dheerajodha In case it helps, we have some setup guides for different operating systems that should help with getting the project building successfully (when running `mvn clean install`, the tests are executed as well):

https://wildfly-security.github.io/wildfly-elytron/guides/

@Skyllarr Would you be able to take a quick look at the error Dheeraj is running into when building?

**Comment by dheerajodha** [comment]
Thank you @fjuma for guiding me to the guides, I re-ran the `mvn clean install` (on both the branches: ELY-2467 and 1.x after updating them) just to make sure, and now I get the error in `WildFly Elytron - HTTP OIDC` (attached the files below). I'm not sure what's happening here, maybe this is a false positive...

[org.wildfly.security.http.oidc.OidcTest.txt](https://github.com/wildfly-security/wildfly-elytron/files/9880445/org.wildfly.security.http.oidc.OidcTest.txt)

[org.wildfly.security.http.oidc.BearerTest.txt](https://github.com/wildfly-security/wildfly-elytron/files/9880458/org.wildfly.security.http.oidc.BearerTest.txt)

I don't want to take up much of your time, I just want to make sure that the changes done as part of this PR don't break anything.

**Pull request merged**
