### PR TITLE
[ELY-1826] Cannot connect to management interface with Java Security Manager enabled

### PR DESCRIPTION
**Pull request by ivassile**
JBEAP(7.2.z): https://issues.jboss.org/browse/JBEAP-17004
Upstream issue: https://issues.jboss.org/browse/ELY-1826
This issue has been resolved upstream as part of refactoring in commit [1].

[1] https://github.com/wildfly-security/wildfly-elytron/commit/2cfa1c61346fbd6ad780ba5085c229e875652867#diff-9ad62980379a45e80f38d71d338c2878

### CODE REVIEW

**Comment by fjuma** [comment]
@ivassile Thanks for the PR! Just a minor comment, the title and commit message should reference an ELY issue instead of a JBEAP issue.

**Comment by ivassile** [comment]
@fjuma I know about this rule, but we don't have specific upstream issue for the downstream issue JBEAP-17004. That's why I explained that upstream is not required and the upstream commit was part of refactoring (ELY-1711) unrelated to that issue.

**Comment by ivassile** [comment]
Created upstream ELY-1826 and updated the description.

**Comment by fjuma** [comment]
Perfect, thanks @ivassile! Just need the commit message updated to reference ELY-1826 and then this will be ready to be merged.

**Comment by ivassile** [comment]
@fjuma Modified the commit message.

**Pull request merged**
