### PR TITLE
Verify certificates using credential acquisition in addition to evidence verification; get Principal separately

### PR DESCRIPTION
**Pull request by dmlloyd**

### CODE REVIEW

**Comment by darranl** [comment]
So is the plan to then remove X509PeerCertificateChainEvidence ?

**Comment by dmlloyd** [comment]
I don't know that we can call it a "plan" just yet.  But it is a possibility and I"d like to see it happen.

**Comment by darranl** [comment]
I am going to be continuing with some changes for SSL renegotiation tomorrow - I may see if I this fits with the client cert mechanism.

**Comment by dmlloyd** [comment]
One problem we might hit is that some realms (like LDAP) seem to not necessarily store the actual certificate.  This is what made me think maybe credentials should be considered verifiable too, as there seems to be some consistent overlap between the two concepts.

**Comment by darranl** [comment]
True, that is a good point we need to remember - in general we can't always 100% guarantee acquisition is an option.

**Pull request merged**
