### PR TITLE
[ELY-2460] Add Override annotation to BCryptPassword#getParameterSpec

### PR DESCRIPTION
**Pull request by anilabhabaral**
https://issues.redhat.com/browse/ELY-2460

### CODE REVIEW

**Review by skyllarr — APPROVED** [review]

**Comment by skyllarr** [comment]
@anilabhabaral Thank you!

**Comment by skyllarr** [comment]
@anilabhabaral Just a minor, if you look at your commit message you can see the following:

```
[ELY-2460] Add Override annotation to BCryptPassword#getParameterSpec

[ELY-2460]: Add Override annotation to BCryptPassword#getParameterSpec
[ELY-2460] Add Override annotation to BCryptPassword#getParameterSpec
```

It would be better to remove the duplication that is in the commit description. Thank you!

**Comment by anilabhabaral** [comment]
@Skyllarr I made the suggested change. Please check.

**Comment by skyllarr** [comment]
@anilabhabaral Looks great! We require 2 approvals before the commits can be merged, so @fjuma will provide a second review this week as well. Thank you!

**Review by fjuma — APPROVED** [review]
Thanks @anilabhabaral!

**Comment by anilabhabaral** [comment]
Thanks @Skyllarr @fjuma

**Pull request merged**
