### PR TITLE
[ELY-2469] Update deprecated assertThat method in JACC, credential store and sasl test cases

### PR DESCRIPTION
**Pull request by dheerajodha**
https://issues.redhat.com/browse/ELY-2469

### CODE REVIEW

**Comment by dheerajodha** [comment]
**Quick question:** In the description of this issue, there are only 3 files mentioned where we'd need to update the imports.
But when I [searched for the deprecated import](https://github.com/wildfly-security/wildfly-elytron/search?q=org.junit.Assert.assertThat) in this repository I found an additional file where the same import needs to be updated as well: [SaslFactoriesApiTest.java](https://github.com/wildfly-security/wildfly-elytron/blob/febc8a60e7cd34d376929e20129f0b919e2f11c1/tests/base/src/test/java/org/wildfly/security/sasl/test/SaslFactoriesApiTest.java)

Can you please tell me if I should update the import in this additional file as part of this PR or just leave it as it is?

**Comment by skyllarr** [comment]
Hello @dheerajodha and thank you for the PR! Feel free to update it in [SaslFactoriesApiTest.java](https://github.com/wildfly-security/wildfly-elytron/blob/febc8a60e7cd34d376929e20129f0b919e2f11c1/tests/base/src/test/java/org/wildfly/security/sasl/test/SaslFactoriesApiTest.java) as well. You can update the commit message also

**Review by skyllarr — APPROVED** [review]

**Review by fjuma — APPROVED** [review]
Thanks @dheerajodha!

**Comment by dheerajodha** [comment]
Thank you very much! @Skyllarr and @fjuma :D

**Pull request merged**
