### PR TITLE
[ELY-1953] Elytron tool command execution fails with java.nio.file.No…

### PR DESCRIPTION
**Pull request by ivassile**
…SuchFileException

Issue: https://issues.redhat.com/browse/JBEAP-19498
Upstream issue: https://issues.redhat.com/browse/ELY-1953
Upstream PR: https://github.com/wildfly-security/wildfly-elytron/pull/1385

### CODE REVIEW

**Comment by darranl** [comment]
@ivassile we probably should have had the original PR targeting this branch if needed so soon.

**Comment by ivassile** [comment]
@darranl Sorry, but I noticed that the issue is a blocker and decided to backport it. I also asked Ricardo [1] if we need it also for EAP 7.2.9. The problem with EAP 7.2.9 is that we already released Elytron.

[1] https://issues.redhat.com/browse/JBEAP-19498?focusedCommentId=14099643&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14099643

**Comment by darranl** [comment]
I can do another 7.2.9 tag if there is time, just submit against the 1.6.x branch.

Tuesday is looking like my best day next week for a round of tagging.

**Comment by ivassile** [comment]
@darranl Sounds good. I'll backport the issue to 1.6.x branch. We have time because EAP 7.2.9 tag has been moved back to be in sync with EAP 7.3.2 tag.

**Comment by ivassile** [comment]
@darranl I need to confirm it with Ricardo, but we may not need to fix the issue in 7.2.9 because according to ELY-1953 [1] this is regression for 7.3.0.GA. 

[1] https://issues.redhat.com/browse/ELY-1953

**Comment by darranl** [comment]
Ok no problem - just let me know.  Tuesday next week seems a good time to catch up on these branches if we do need it.

**Comment by ivassile** [comment]
@darranl Ricardo just confirmed on JBEAP-19498 that this issue only affects 7.3.x and we don't need to port it to 1.6.x.

**Pull request merged**
