### PR TITLE
[ELY-2545] referral-mode="ignore" and filter-base-dn=rootDN cause javax.naming.PartialResultException

### PR DESCRIPTION
**Pull request by hokuda**
https://issues.redhat.com/browse/ELY-2462
Please review this PR.
Thanks.

### CODE REVIEW

**Comment by jessicarod7** [comment]
Hey, could you add a link to the JIRA issue in the description? Ex. #1894 

Looks good at first glance, but I'm not as familiar with AD so I can't really review it.

**Comment by hokuda** [comment]
@cam-rod Thanks for paying attention to this.
JIRA URL is https://issues.redhat.com/browse/ELY-2545

**Review by darranl — APPROVED** [review]

**Comment by fjuma** [comment]
@PrarthonaPaul Would you be able to get these changes into a new PR against the 2.x branch?

**Comment by PrarthonaPaul** [comment]
> @PrarthonaPaul Would you be able to get these changes into a new PR against the 2.x branch?

I have added a new PR here: https://github.com/wildfly-security/wildfly-elytron/pull/2117

**Comment by fjuma** [comment]
Thanks very much @PrarthonaPaul and @hokuda!

Closing this one since it's now superseded by https://github.com/wildfly-security/wildfly-elytron/pull/2117.

**Pull request closed without merging**
