### PR TITLE
[ELY-1833] KeyStoreCredentialStore does not use Provider[] for passwords.

### PR DESCRIPTION
**Pull request by ivassile**
https://issues.jboss.org/browse/ELY-1833

### CODE REVIEW

**Comment by ivassile** [comment]
@Skyllarr After the review I corrected an issue and added the new option to validAttribtues list.

**Comment by darranl** [comment]
It may be better to handle this with https://github.com/wildfly-security/wildfly-elytron/pull/1336 and combine into a single RFE.

**Comment by ivassile** [comment]
> It may be better to handle this with #1336 and combine into a single RFE.

@darranl ok. I'll combine the PRs and create a singe RFE

**Comment by ivassile** [comment]
Replaced by https://github.com/wildfly-security/wildfly-elytron/pull/1341

**Pull request closed without merging**
