### PR TITLE
[ELY-709] custom GSSManager in SPNEGO

### PR DESCRIPTION
**Pull request by honza889**
https://issues.jboss.org/browse/ELY-709

### CODE REVIEW

**Comment by darranl** [comment]
This one also needs a rebase.

**Comment by honza889** [comment]
rebased

**Comment by dmlloyd** [comment]
I'm not super-excited about using properties for this.  In SASL GS2 for example, we inject a GSSManager to detect the mechanisms from, and that combination makes a wholly new mechanism.  In this case though, is there only one actual mechanism?

**Comment by honza889** [comment]
What do you mean? That it is not useful to allow setting of GSSManager here, or that it should by done by different way?
(It looks property is only way to pass something into HttpServerAuthenticationMechanismFactory)

**Comment by dmlloyd** [comment]
I guess I'm not certain.  SPNEGO is seemingly only useful when there are GSS mechanism to actually negotiate.  A custom GSSManager would have to contain an SPNEGO implementation as well as secondary mechanism(s) to negotiate.  However, such a GSSManager would then lose support for SPNEGO negotiating mechanisms present in other GSSManagers.  So maybe this change is not useful until/unless there is a GSSManager which can aggregate SPNEGO negotiation across multiple providers.

**Comment by honza889** [comment]
Rebased.

**Pull request merged**
