### PR TITLE
ELY-2638 Simplify test assertions in SSLAuthenticationTest

### PR DESCRIPTION
**Pull request by nidhiazad**
https://issues.redhat.com/browse/ELY-2638

### CODE REVIEW

**Comment by skyllarr** [comment]
Hello @nidhiazad , please make sure there is 1 commit for 1 issue. Currently, there is 1 commit with the commit message "Your commit message here" , so please update it. Please also, create a jira acount and assign the issue to you, so other participants know that it was taken. Thank you!

**Comment by nidhiazad** [comment]
Hi team,
I have created a jira account on mail id ***@***.*** . Is
there any JIRA board for the wildfly issues. I want to assign this issue to
myself on JIRA https://issues.redhat.com/browse/ELY-2630?filter=12383825.
How can i do that? Can you please help?

Thanks and Regards
Nidhi

**Comment by nidhiazad** [comment]
Able to do now.

**Comment by skyllarr** [comment]
@nidhiazad I will explain this on the preseentation

**Comment by skyllarr** [comment]
Hello @nidhiazad , just a minor, please make sure that there is 1 commit for 1 issue. Thank you!

**Comment by nidhiazad** [comment]
sure I am following this practice of creating 1 branch , 1PR  for 1 issue

**Comment by PrarthonaPaul** [comment]
> sure I am following this practice of creating 1 branch , 1PR for 1 issue

Since this issue has another PR, which you are working on, you can go ahead and close this one when you can. Thanks!

**Comment by nidhiazad** [comment]
Closing this PR. Thanks

**Pull request closed without merging**
