### PR TITLE
[ELY-2458] Use already defined constant HttpConstants.DIGEST_NAME instead of hardcoding DIGEST multiple times in HttpAuthenticationFactory

### PR DESCRIPTION
**Pull request by albertotn**
See https://issues.redhat.com/browse/ELY-2458

### CODE REVIEW

**Review by skyllarr — DISMISSED** [review]

**Comment by skyllarr** [comment]
@albertotn Changes looks good, just a minor, please put issue number at the beginning of the commit message so this can be merged. Thanks!

**Comment by skyllarr** [comment]
@albertotn Please squash the commits into 1. This can be done by using interactive rebase: git rebase -i HEAD~3 and updating the commits as needed. Then you can force push to your branch. Thanks!

**Comment by skyllarr** [comment]
@albertotn You can take a look at the video we created about interactive squashing here https://www.youtube.com/watch?v=NUfyS-2vTfo&t

**Comment by albertotn** [comment]
closed, replaced by https://github.com/wildfly-security/wildfly-elytron/pull/1817

**Pull request closed without merging**
