### PR TITLE
[ELY-198] Associate a Supplier<Provider[]> with the SecurityDomain 

### PR DESCRIPTION
**Pull request by darranl**
So it can be used for subsequent mechanism loading.

### CODE REVIEW

**Comment by dmlloyd** [comment]
What does the security domain need this for?

**Comment by darranl** [comment]
This is for pulling HTTP authentication mechanisms from the registered providers, should also look at getting SASL to do the same.

**Comment by dmlloyd** [comment]
For SASL my plan was to have the providers be fed to each configuration, which allows each configuration to support different/unrelated mechanisms; same thing for SSL.

**Comment by dmlloyd** [comment]
I'm still not 100% sure that we should do this.  I think the providers should be given to the individual mechanism factory methods, because it's not clear to me that (for example) SSL and SASL will always prefer the same providers in the same order.

That said... I guess we could consider having a fallback default, as long as it is possible to override the default in both API and configuration for SASL, SSL, HTTP, etc.

**Comment by darranl** [comment]
Just place on hold for the moment, will agree a way forward this week as we need to discuss mechanism selection / domain association etc...

**Comment by darranl** [comment]
Closing as we have agreed an alternative approach to handle mechanism factories and the domain relationship.

**Pull request closed without merging**
