### PR TITLE
[ELY-2670] Upgrade org.jboss.slf4j:slf4j-jboss-logmanager from 1.0.4.GA to 1.2.0.Final

### PR DESCRIPTION
**Pull request by areebniyas**
Refer $subject.

Resolves issue - https://issues.redhat.com/browse/ELY-2670?filter=12383825

### CODE REVIEW

**Review by PrarthonaPaul — APPROVED** [review]
LGTM! 
Thanks @areebniyas

**Review by skyllarr — APPROVED** [review]

**Comment by PrarthonaPaul** [comment]
Hi @areebniyas 
It seems that this branch is conflicting with the main branch. 
Would you be able to rebase and resolve the conflicts? If you have any questions about how to do this, please feel free to let me know :) 
Thanks!

**Comment by areebniyas** [comment]
Resolved the conflict, let me know if it looks okay @PrarthonaPaul

**Comment by PrarthonaPaul** [comment]
Looks good. 
Thanks @areebniyas

**Pull request merged**
